package schemagen

import (
	"bytes"
	"fmt"
	"maps"
	"slices"
	"strings"

	"github.com/flanksource/uir"
)

// GeneratePythonStatementKinds returns python/statement_kinds.py: the statement
// kinds uir.StatementMarshaler registers and the refinements each kind accepts
// from outside its own ':'-hierarchy. The Python encoder checks a refined
// statement type against these, so it accepts exactly what Go decodes.
func GeneratePythonStatementKinds() []byte {
	var out bytes.Buffer
	out.WriteString(`# Code generated by cmd/genschema from uir.StatementMarshaler; DO NOT EDIT.
# Run ` + "`make schema`" + ` after registering a statement kind.
"""The statement kinds Go registers, which a refined statement type resolves to."""

# Every kind uir.StatementMarshaler registers.
REGISTERED_KINDS = frozenset([
`)
	for _, kind := range uir.StatementMarshaler.Kinds() {
		fmt.Fprintf(&out, "    %q,\n", kind)
	}
	out.WriteString(`])

# The refinements a kind accepts from outside its own ':'-hierarchy.
CROSS_HIERARCHY = {
`)
	cross := uir.StatementMarshaler.CrossHierarchy()
	for _, kind := range slices.Sorted(maps.Keys(cross)) {
		refinements := slices.Sorted(slices.Values(cross[kind]))
		quoted := make([]string, len(refinements))
		for i, refinement := range refinements {
			quoted[i] = fmt.Sprintf("%q", refinement)
		}
		fmt.Fprintf(&out, "    %q: frozenset([%s]),\n", kind, strings.Join(quoted, ", "))
	}
	out.WriteString("}\n")
	return out.Bytes()
}
