// Command genquery regenerates the PEG parser for the UIR query language.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"os/exec"
)

const generatedNotice = "// Code generated by go tool peg -noast -switch grammar.peg; DO NOT EDIT."

func main() {
	command := exec.Command("go", "tool", "peg", "-noast", "-switch", "grammar.peg")
	command.Stdout = os.Stdout
	command.Stderr = os.Stderr
	if err := command.Run(); err != nil {
		panic(fmt.Errorf("generate UIR query parser: %w", err))
	}
	path := "grammar.peg.go"
	data, err := os.ReadFile(path)
	if err != nil {
		panic(fmt.Errorf("read generated UIR query parser: %w", err))
	}
	start := bytes.Index(data, []byte("// Code generated by "))
	if start < 0 {
		panic("generated UIR query parser has no generated-code notice")
	}
	end := bytes.IndexByte(data[start:], '\n')
	if end < 0 {
		panic("generated UIR query parser has an incomplete generated-code notice")
	}
	withoutNotice := append([]byte(nil), data[:start]...)
	withoutNotice = append(withoutNotice, data[start+end+1:]...)
	normalized := append([]byte(generatedNotice+"\n\n"), withoutNotice...)
	formatted, err := format.Source(normalized)
	if err != nil {
		panic(fmt.Errorf("format generated UIR query parser: %w", err))
	}
	if err := os.WriteFile(path, formatted, 0o644); err != nil {
		panic(fmt.Errorf("normalize generated UIR query parser: %w", err))
	}
}
