package query

type queryGrammar Peg {
    parserState
}

Query <- _ Set _ !.
Set <- Intersection (_ UnionOperator _ Intersection)*
Intersection <- Chain (_ IntersectionOperator _ Chain)*
Chain <- Primary (_ (PathStep / Step / Modifier))*
Primary <- Selector / Symbol / Open _ Set _ Close
Step <- Relation (_ Filter)* (_ Primary (_ Modifier)*)?

Selector <- <SelectorText> { p.addToken("selector", text) }
Modifier <- <('+' / '-') SelectorText> { p.addToken("modifier", text) }
SelectorText <- ('pkg' / 'mod' / 'func' / 'field' / 'struct') ':' SelectorValue (':' SelectorValue)?
SelectorValue <- ([A-Za-z0-9_./*?@#$!] / '-' / '\\' .)+
Symbol <- <[A-Za-z_]([A-Za-z0-9_./*] / '-')*> { p.addToken("symbol", text) }
Relation <- Transitive / Implementers / Methods / Incoming / Outgoing / Definition / Writes
Transitive <- '<<' <[0-9]*> { p.addToken("relation", "<<" + text) }
Implementers <- ':impl' { p.addToken("relation", ":impl") }
Methods <- ':methods' { p.addToken("relation", ":methods") }
Incoming <- '<' { p.addToken("relation", "<") }
Outgoing <- '>' { p.addToken("relation", ">") }
Definition <- '=' { p.addToken("relation", "=") }
Writes <- '~w' { p.addToken("relation", "~w") }
Filter <- RoleFilter / ValueFilter
RoleFilter <- <'~w'> { p.addToken("filter", text) }
ValueFilter <- <('-f' / '+pkg' / '-pkg')> { p.addToken("filter", text) } Spacing Value
Value <- <([A-Za-z0-9_./*] / '-')+> { p.addToken("value", text) }

PathStep <- PathOperator _ Primary
PathOperator <- '>>' <[0-9]*> { p.addToken("path", ">>" + text) }
UnionOperator <- '|' { p.addToken("or", "|") }
IntersectionOperator <- '&' { p.addToken("and", "&") }
Open <- '(' { p.addToken("open", "(") }
Close <- ')' { p.addToken("close", ")") }

Spacing <- [ \t\r\n]+
_ <- [ \t\r\n]*
