// Code generated by go tool peg -noast -switch grammar.peg; DO NOT EDIT.

package query

import (
	"fmt"
	"sort"
	"strconv"
)

const endSymbol rune = 1114112

/* The rule types inferred from the grammar are below. */
type pegRule uint8

const (
	ruleUnknown pegRule = iota
	ruleQuery
	ruleSet
	ruleIntersection
	ruleChain
	rulePrimary
	ruleStep
	ruleSelector
	ruleModifier
	ruleSelectorText
	ruleSelectorPrefix
	ruleSelectorValue
	ruleEntityField
	ruleEntityName
	ruleEntityChar
	ruleRelationName
	ruleSymbol
	ruleQuoted
	ruleQuotedText
	ruleRelation
	ruleTransitive
	ruleImplementers
	ruleInheritors
	ruleMethods
	ruleIncoming
	ruleOutgoing
	ruleDefinition
	ruleWrites
	ruleFilter
	ruleRoleFilter
	ruleValueFilter
	ruleValue
	rulePathStep
	rulePathOperator
	ruleUnionOperator
	ruleIntersectionOperator
	ruleOpen
	ruleClose
	ruleSpacing
	rule_
	rulePegText
	ruleAction0
	ruleAction1
	ruleAction2
	ruleAction3
	ruleAction4
	ruleAction5
	ruleAction6
	ruleAction7
	ruleAction8
	ruleAction9
	ruleAction10
	ruleAction11
	ruleAction12
	ruleAction13
	ruleAction14
	ruleAction15
	ruleAction16
	ruleAction17
	ruleAction18
	ruleAction19
	ruleAction20
)

var rul3s = [...]string{
	"Unknown",
	"Query",
	"Set",
	"Intersection",
	"Chain",
	"Primary",
	"Step",
	"Selector",
	"Modifier",
	"SelectorText",
	"SelectorPrefix",
	"SelectorValue",
	"EntityField",
	"EntityName",
	"EntityChar",
	"RelationName",
	"Symbol",
	"Quoted",
	"QuotedText",
	"Relation",
	"Transitive",
	"Implementers",
	"Inheritors",
	"Methods",
	"Incoming",
	"Outgoing",
	"Definition",
	"Writes",
	"Filter",
	"RoleFilter",
	"ValueFilter",
	"Value",
	"PathStep",
	"PathOperator",
	"UnionOperator",
	"IntersectionOperator",
	"Open",
	"Close",
	"Spacing",
	"_",
	"PegText",
	"Action0",
	"Action1",
	"Action2",
	"Action3",
	"Action4",
	"Action5",
	"Action6",
	"Action7",
	"Action8",
	"Action9",
	"Action10",
	"Action11",
	"Action12",
	"Action13",
	"Action14",
	"Action15",
	"Action16",
	"Action17",
	"Action18",
	"Action19",
	"Action20",
}

type token32 struct {
	pegRule
	begin, end uint32
}

func (t *token32) String() string {
	return fmt.Sprintf("\x1B[34m%v\x1B[m %v %v", rul3s[t.pegRule], t.begin, t.end)
}

type queryGrammar struct {
	parserState

	Buffer string
	buffer []rune
	rules  [62]func() bool
	parse  func(rule ...int) error
	reset  func()
	Pretty bool
}

func (p *queryGrammar) Parse(rule ...int) error {
	return p.parse(rule...)
}

func (p *queryGrammar) Reset() {
	p.reset()
}

type textPosition struct {
	line, symbol int
}

type textPositionMap map[int]textPosition

func translatePositions(buffer []rune, positions []int) textPositionMap {
	length, translations, j, line, symbol := len(positions), make(textPositionMap, len(positions)), 0, 1, 0
	sort.Ints(positions)

search:
	for i, c := range buffer {
		if c == '\n' {
			line, symbol = line+1, 0
		} else {
			symbol++
		}
		if i == positions[j] {
			translations[positions[j]] = textPosition{line, symbol}
			for j++; j < length; j++ {
				if i != positions[j] {
					continue search
				}
			}
			break search
		}
	}

	return translations
}

type parseError struct {
	p   *queryGrammar
	max token32
}

func (e *parseError) Error() string {
	tokens, err := []token32{e.max}, "\n"
	positions, p := make([]int, 2*len(tokens)), 0
	for _, token := range tokens {
		positions[p], p = int(token.begin), p+1
		positions[p], p = int(token.end), p+1
	}
	translations := translatePositions(e.p.buffer, positions)
	format := "parse error near %v (line %v symbol %v - line %v symbol %v):\n%v\n"
	if e.p.Pretty {
		format = "parse error near \x1B[34m%v\x1B[m (line %v symbol %v - line %v symbol %v):\n%v\n"
	}
	for _, token := range tokens {
		begin, end := int(token.begin), int(token.end)
		err += fmt.Sprintf(format,
			rul3s[token.pegRule],
			translations[begin].line, translations[begin].symbol,
			translations[end].line, translations[end].symbol,
			strconv.Quote(string(e.p.buffer[begin:end])))
	}

	return err
}

func Pretty(pretty bool) func(*queryGrammar) error {
	return func(p *queryGrammar) error {
		p.Pretty = pretty
		return nil
	}
}

func (p *queryGrammar) Init(options ...func(*queryGrammar) error) error {
	var (
		max                  token32
		position, tokenIndex uint32
		buffer               []rune
		text                 string
	)
	for _, option := range options {
		err := option(p)
		if err != nil {
			return err
		}
	}
	p.reset = func() {
		max = token32{}
		position, tokenIndex = 0, 0

		p.buffer = []rune(p.Buffer)
		if len(p.buffer) == 0 || p.buffer[len(p.buffer)-1] != endSymbol {
			p.buffer = append(p.buffer, endSymbol)
		}
		buffer = p.buffer
	}
	p.reset()

	_rules := p.rules
	p.parse = func(rule ...int) error {
		r := 1
		if len(rule) > 0 {
			r = rule[0]
		}
		matches := p.rules[r]()
		if matches {
			return nil
		}
		return &parseError{p, max}
	}

	add := func(rule pegRule, begin uint32) {
		tokenIndex++
		if begin != position && position > max.end {
			max = token32{rule, begin, position}
		}
	}

	matchDot := func() bool {
		if buffer[position] != endSymbol {
			position++
			return true
		}
		return false
	}

	/*matchChar := func(c byte) bool {
		if buffer[position] == c {
			position++
			return true
		}
		return false
	}*/

	/*matchRange := func(lower byte, upper byte) bool {
		if c := buffer[position]; c >= lower && c <= upper {
			position++
			return true
		}
		return false
	}*/

	_rules = [...]func() bool{
		nil,
		/* 0 Query <- <(_ Set _ !.)> */
		func() bool {
			position0, tokenIndex0 := position, tokenIndex
			{
				position1 := position
				if !_rules[rule_]() {
					goto l0
				}
				if !_rules[ruleSet]() {
					goto l0
				}
				if !_rules[rule_]() {
					goto l0
				}
				{
					position2, tokenIndex2 := position, tokenIndex
					if !matchDot() {
						goto l2
					}
					goto l0
				l2:
					position, tokenIndex = position2, tokenIndex2
				}
				add(ruleQuery, position1)
			}
			return true
		l0:
			position, tokenIndex = position0, tokenIndex0
			return false
		},
		/* 1 Set <- <(Intersection (_ UnionOperator _ Intersection)*)> */
		func() bool {
			position3, tokenIndex3 := position, tokenIndex
			{
				position4 := position
				if !_rules[ruleIntersection]() {
					goto l3
				}
			l5:
				{
					position6, tokenIndex6 := position, tokenIndex
					if !_rules[rule_]() {
						goto l6
					}
					if !_rules[ruleUnionOperator]() {
						goto l6
					}
					if !_rules[rule_]() {
						goto l6
					}
					if !_rules[ruleIntersection]() {
						goto l6
					}
					goto l5
				l6:
					position, tokenIndex = position6, tokenIndex6
				}
				add(ruleSet, position4)
			}
			return true
		l3:
			position, tokenIndex = position3, tokenIndex3
			return false
		},
		/* 2 Intersection <- <(Chain (_ IntersectionOperator _ Chain)*)> */
		func() bool {
			position7, tokenIndex7 := position, tokenIndex
			{
				position8 := position
				if !_rules[ruleChain]() {
					goto l7
				}
			l9:
				{
					position10, tokenIndex10 := position, tokenIndex
					if !_rules[rule_]() {
						goto l10
					}
					if !_rules[ruleIntersectionOperator]() {
						goto l10
					}
					if !_rules[rule_]() {
						goto l10
					}
					if !_rules[ruleChain]() {
						goto l10
					}
					goto l9
				l10:
					position, tokenIndex = position10, tokenIndex10
				}
				add(ruleIntersection, position8)
			}
			return true
		l7:
			position, tokenIndex = position7, tokenIndex7
			return false
		},
		/* 3 Chain <- <(Primary (_ (PathStep / Step / Modifier))*)> */
		func() bool {
			position11, tokenIndex11 := position, tokenIndex
			{
				position12 := position
				if !_rules[rulePrimary]() {
					goto l11
				}
			l13:
				{
					position14, tokenIndex14 := position, tokenIndex
					if !_rules[rule_]() {
						goto l14
					}
					{
						position15, tokenIndex15 := position, tokenIndex
						if !_rules[rulePathStep]() {
							goto l16
						}
						goto l15
					l16:
						position, tokenIndex = position15, tokenIndex15
						if !_rules[ruleStep]() {
							goto l17
						}
						goto l15
					l17:
						position, tokenIndex = position15, tokenIndex15
						if !_rules[ruleModifier]() {
							goto l14
						}
					}
				l15:
					goto l13
				l14:
					position, tokenIndex = position14, tokenIndex14
				}
				add(ruleChain, position12)
			}
			return true
		l11:
			position, tokenIndex = position11, tokenIndex11
			return false
		},
		/* 4 Primary <- <(Selector / EntityField / Symbol / (Open _ Set _ Close))> */
		func() bool {
			position18, tokenIndex18 := position, tokenIndex
			{
				position19 := position
				{
					position20, tokenIndex20 := position, tokenIndex
					if !_rules[ruleSelector]() {
						goto l21
					}
					goto l20
				l21:
					position, tokenIndex = position20, tokenIndex20
					if !_rules[ruleEntityField]() {
						goto l22
					}
					goto l20
				l22:
					position, tokenIndex = position20, tokenIndex20
					if !_rules[ruleSymbol]() {
						goto l23
					}
					goto l20
				l23:
					position, tokenIndex = position20, tokenIndex20
					if !_rules[ruleOpen]() {
						goto l18
					}
					if !_rules[rule_]() {
						goto l18
					}
					if !_rules[ruleSet]() {
						goto l18
					}
					if !_rules[rule_]() {
						goto l18
					}
					if !_rules[ruleClose]() {
						goto l18
					}
				}
			l20:
				add(rulePrimary, position19)
			}
			return true
		l18:
			position, tokenIndex = position18, tokenIndex18
			return false
		},
		/* 5 Step <- <(Relation (_ Filter)* (_ Primary (_ Modifier)*)?)> */
		func() bool {
			position24, tokenIndex24 := position, tokenIndex
			{
				position25 := position
				if !_rules[ruleRelation]() {
					goto l24
				}
			l26:
				{
					position27, tokenIndex27 := position, tokenIndex
					if !_rules[rule_]() {
						goto l27
					}
					if !_rules[ruleFilter]() {
						goto l27
					}
					goto l26
				l27:
					position, tokenIndex = position27, tokenIndex27
				}
				{
					position28, tokenIndex28 := position, tokenIndex
					if !_rules[rule_]() {
						goto l28
					}
					if !_rules[rulePrimary]() {
						goto l28
					}
				l30:
					{
						position31, tokenIndex31 := position, tokenIndex
						if !_rules[rule_]() {
							goto l31
						}
						if !_rules[ruleModifier]() {
							goto l31
						}
						goto l30
					l31:
						position, tokenIndex = position31, tokenIndex31
					}
					goto l29
				l28:
					position, tokenIndex = position28, tokenIndex28
				}
			l29:
				add(ruleStep, position25)
			}
			return true
		l24:
			position, tokenIndex = position24, tokenIndex24
			return false
		},
		/* 6 Selector <- <(<SelectorText> Action0)> */
		func() bool {
			position32, tokenIndex32 := position, tokenIndex
			{
				position33 := position
				{
					position34 := position
					if !_rules[ruleSelectorText]() {
						goto l32
					}
					begin := position34
					end := position
					text = string(buffer[begin:end])
				}
				if !_rules[ruleAction0]() {
					goto l32
				}
				add(ruleSelector, position33)
			}
			return true
		l32:
			position, tokenIndex = position32, tokenIndex32
			return false
		},
		/* 7 Modifier <- <(<(('+' / '-') SelectorText)> Action1)> */
		func() bool {
			position35, tokenIndex35 := position, tokenIndex
			{
				position36 := position
				{
					position37 := position
					{
						position38, tokenIndex38 := position, tokenIndex
						if buffer[position] != rune('+') {
							goto l39
						}
						position++
						goto l38
					l39:
						position, tokenIndex = position38, tokenIndex38
						if buffer[position] != rune('-') {
							goto l35
						}
						position++
					}
				l38:
					if !_rules[ruleSelectorText]() {
						goto l35
					}
					begin := position37
					end := position
					text = string(buffer[begin:end])
				}
				if !_rules[ruleAction1]() {
					goto l35
				}
				add(ruleModifier, position36)
			}
			return true
		l35:
			position, tokenIndex = position35, tokenIndex35
			return false
		},
		/* 8 SelectorText <- <(SelectorPrefix ':' SelectorValue (':' SelectorValue)?)> */
		func() bool {
			position40, tokenIndex40 := position, tokenIndex
			{
				position41 := position
				if !_rules[ruleSelectorPrefix]() {
					goto l40
				}
				if buffer[position] != rune(':') {
					goto l40
				}
				position++
				if !_rules[ruleSelectorValue]() {
					goto l40
				}
				{
					position42, tokenIndex42 := position, tokenIndex
					if buffer[position] != rune(':') {
						goto l42
					}
					position++
					if !_rules[ruleSelectorValue]() {
						goto l42
					}
					goto l43
				l42:
					position, tokenIndex = position42, tokenIndex42
				}
			l43:
				add(ruleSelectorText, position41)
			}
			return true
		l40:
			position, tokenIndex = position40, tokenIndex40
			return false
		},
		/* 9 SelectorPrefix <- <(('p' 'a' 'c' 'k' 'a' 'g' 'e') / ('m' 'o' 'd' 'u' 'l' 'e') / ('m' 'e' 't' 'h' 'o' 'd') / ('f' 'i' 'e' 'l' 'd') / ('p' 'a' 't' 'h') / ((&('k') ('k' 'i' 'n' 'd')) | (&('m') ('m' 'o' 'd')) | (&('p') ('p' 'k' 'g')) | (&('v') ('v' 'a' 'r')) | (&('a') ('a' 'l' 'l')) | (&('t') ('t' 'y' 'p' 'e')) | (&('f') ('f' 'u' 'n' 'c')) | (&('s') ('s' 't' 'r' 'u' 'c' 't'))))> */
		func() bool {
			position44, tokenIndex44 := position, tokenIndex
			{
				position45 := position
				{
					position46, tokenIndex46 := position, tokenIndex
					if buffer[position] != rune('p') {
						goto l47
					}
					position++
					if buffer[position] != rune('a') {
						goto l47
					}
					position++
					if buffer[position] != rune('c') {
						goto l47
					}
					position++
					if buffer[position] != rune('k') {
						goto l47
					}
					position++
					if buffer[position] != rune('a') {
						goto l47
					}
					position++
					if buffer[position] != rune('g') {
						goto l47
					}
					position++
					if buffer[position] != rune('e') {
						goto l47
					}
					position++
					goto l46
				l47:
					position, tokenIndex = position46, tokenIndex46
					if buffer[position] != rune('m') {
						goto l48
					}
					position++
					if buffer[position] != rune('o') {
						goto l48
					}
					position++
					if buffer[position] != rune('d') {
						goto l48
					}
					position++
					if buffer[position] != rune('u') {
						goto l48
					}
					position++
					if buffer[position] != rune('l') {
						goto l48
					}
					position++
					if buffer[position] != rune('e') {
						goto l48
					}
					position++
					goto l46
				l48:
					position, tokenIndex = position46, tokenIndex46
					if buffer[position] != rune('m') {
						goto l49
					}
					position++
					if buffer[position] != rune('e') {
						goto l49
					}
					position++
					if buffer[position] != rune('t') {
						goto l49
					}
					position++
					if buffer[position] != rune('h') {
						goto l49
					}
					position++
					if buffer[position] != rune('o') {
						goto l49
					}
					position++
					if buffer[position] != rune('d') {
						goto l49
					}
					position++
					goto l46
				l49:
					position, tokenIndex = position46, tokenIndex46
					if buffer[position] != rune('f') {
						goto l50
					}
					position++
					if buffer[position] != rune('i') {
						goto l50
					}
					position++
					if buffer[position] != rune('e') {
						goto l50
					}
					position++
					if buffer[position] != rune('l') {
						goto l50
					}
					position++
					if buffer[position] != rune('d') {
						goto l50
					}
					position++
					goto l46
				l50:
					position, tokenIndex = position46, tokenIndex46
					if buffer[position] != rune('p') {
						goto l51
					}
					position++
					if buffer[position] != rune('a') {
						goto l51
					}
					position++
					if buffer[position] != rune('t') {
						goto l51
					}
					position++
					if buffer[position] != rune('h') {
						goto l51
					}
					position++
					goto l46
				l51:
					position, tokenIndex = position46, tokenIndex46
					{
						switch buffer[position] {
						case 'k':
							if buffer[position] != rune('k') {
								goto l44
							}
							position++
							if buffer[position] != rune('i') {
								goto l44
							}
							position++
							if buffer[position] != rune('n') {
								goto l44
							}
							position++
							if buffer[position] != rune('d') {
								goto l44
							}
							position++
						case 'm':
							if buffer[position] != rune('m') {
								goto l44
							}
							position++
							if buffer[position] != rune('o') {
								goto l44
							}
							position++
							if buffer[position] != rune('d') {
								goto l44
							}
							position++
						case 'p':
							if buffer[position] != rune('p') {
								goto l44
							}
							position++
							if buffer[position] != rune('k') {
								goto l44
							}
							position++
							if buffer[position] != rune('g') {
								goto l44
							}
							position++
						case 'v':
							if buffer[position] != rune('v') {
								goto l44
							}
							position++
							if buffer[position] != rune('a') {
								goto l44
							}
							position++
							if buffer[position] != rune('r') {
								goto l44
							}
							position++
						case 'a':
							if buffer[position] != rune('a') {
								goto l44
							}
							position++
							if buffer[position] != rune('l') {
								goto l44
							}
							position++
							if buffer[position] != rune('l') {
								goto l44
							}
							position++
						case 't':
							if buffer[position] != rune('t') {
								goto l44
							}
							position++
							if buffer[position] != rune('y') {
								goto l44
							}
							position++
							if buffer[position] != rune('p') {
								goto l44
							}
							position++
							if buffer[position] != rune('e') {
								goto l44
							}
							position++
						case 'f':
							if buffer[position] != rune('f') {
								goto l44
							}
							position++
							if buffer[position] != rune('u') {
								goto l44
							}
							position++
							if buffer[position] != rune('n') {
								goto l44
							}
							position++
							if buffer[position] != rune('c') {
								goto l44
							}
							position++
						default:
							if buffer[position] != rune('s') {
								goto l44
							}
							position++
							if buffer[position] != rune('t') {
								goto l44
							}
							position++
							if buffer[position] != rune('r') {
								goto l44
							}
							position++
							if buffer[position] != rune('u') {
								goto l44
							}
							position++
							if buffer[position] != rune('c') {
								goto l44
							}
							position++
							if buffer[position] != rune('t') {
								goto l44
							}
							position++
						}
					}

				}
			l46:
				add(ruleSelectorPrefix, position45)
			}
			return true
		l44:
			position, tokenIndex = position44, tokenIndex44
			return false
		},
		/* 10 SelectorValue <- <(Quoted / ((&('\\') ('\\' .)) | (&('-') '-') | (&('!') '!') | (&('$') '$') | (&('#') '#') | (&('@') '@') | (&('?') '?') | (&('*') '*') | (&('/') '/') | (&('.') '.') | (&('_') '_') | (&('0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9') [0-9]) | (&('a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g' | 'h' | 'i' | 'j' | 'k' | 'l' | 'm' | 'n' | 'o' | 'p' | 'q' | 'r' | 's' | 't' | 'u' | 'v' | 'w' | 'x' | 'y' | 'z') [a-z]) | (&('A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | 'H' | 'I' | 'J' | 'K' | 'L' | 'M' | 'N' | 'O' | 'P' | 'Q' | 'R' | 'S' | 'T' | 'U' | 'V' | 'W' | 'X' | 'Y' | 'Z') [A-Z]))+)> */
		func() bool {
			position53, tokenIndex53 := position, tokenIndex
			{
				position54 := position
				{
					position55, tokenIndex55 := position, tokenIndex
					if !_rules[ruleQuoted]() {
						goto l56
					}
					goto l55
				l56:
					position, tokenIndex = position55, tokenIndex55
					{
						switch buffer[position] {
						case '\\':
							if buffer[position] != rune('\\') {
								goto l53
							}
							position++
							if !matchDot() {
								goto l53
							}
						case '-':
							if buffer[position] != rune('-') {
								goto l53
							}
							position++
						case '!':
							if buffer[position] != rune('!') {
								goto l53
							}
							position++
						case '$':
							if buffer[position] != rune('$') {
								goto l53
							}
							position++
						case '#':
							if buffer[position] != rune('#') {
								goto l53
							}
							position++
						case '@':
							if buffer[position] != rune('@') {
								goto l53
							}
							position++
						case '?':
							if buffer[position] != rune('?') {
								goto l53
							}
							position++
						case '*':
							if buffer[position] != rune('*') {
								goto l53
							}
							position++
						case '/':
							if buffer[position] != rune('/') {
								goto l53
							}
							position++
						case '.':
							if buffer[position] != rune('.') {
								goto l53
							}
							position++
						case '_':
							if buffer[position] != rune('_') {
								goto l53
							}
							position++
						case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
							if c := buffer[position]; c < rune('0') || c > rune('9') {
								goto l53
							}
							position++
						case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
							if c := buffer[position]; c < rune('a') || c > rune('z') {
								goto l53
							}
							position++
						default:
							if c := buffer[position]; c < rune('A') || c > rune('Z') {
								goto l53
							}
							position++
						}
					}

				l57:
					{
						position58, tokenIndex58 := position, tokenIndex
						{
							switch buffer[position] {
							case '\\':
								if buffer[position] != rune('\\') {
									goto l58
								}
								position++
								if !matchDot() {
									goto l58
								}
							case '-':
								if buffer[position] != rune('-') {
									goto l58
								}
								position++
							case '!':
								if buffer[position] != rune('!') {
									goto l58
								}
								position++
							case '$':
								if buffer[position] != rune('$') {
									goto l58
								}
								position++
							case '#':
								if buffer[position] != rune('#') {
									goto l58
								}
								position++
							case '@':
								if buffer[position] != rune('@') {
									goto l58
								}
								position++
							case '?':
								if buffer[position] != rune('?') {
									goto l58
								}
								position++
							case '*':
								if buffer[position] != rune('*') {
									goto l58
								}
								position++
							case '/':
								if buffer[position] != rune('/') {
									goto l58
								}
								position++
							case '.':
								if buffer[position] != rune('.') {
									goto l58
								}
								position++
							case '_':
								if buffer[position] != rune('_') {
									goto l58
								}
								position++
							case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
								if c := buffer[position]; c < rune('0') || c > rune('9') {
									goto l58
								}
								position++
							case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
								if c := buffer[position]; c < rune('a') || c > rune('z') {
									goto l58
								}
								position++
							default:
								if c := buffer[position]; c < rune('A') || c > rune('Z') {
									goto l58
								}
								position++
							}
						}

						goto l57
					l58:
						position, tokenIndex = position58, tokenIndex58
					}
				}
			l55:
				add(ruleSelectorValue, position54)
			}
			return true
		l53:
			position, tokenIndex = position53, tokenIndex53
			return false
		},
		/* 11 EntityField <- <(<(!(SelectorPrefix ':') EntityName ':' !(RelationName !EntityChar) (Quoted / EntityChar+))> Action2)> */
		func() bool {
			position61, tokenIndex61 := position, tokenIndex
			{
				position62 := position
				{
					position63 := position
					{
						position64, tokenIndex64 := position, tokenIndex
						if !_rules[ruleSelectorPrefix]() {
							goto l64
						}
						if buffer[position] != rune(':') {
							goto l64
						}
						position++
						goto l61
					l64:
						position, tokenIndex = position64, tokenIndex64
					}
					if !_rules[ruleEntityName]() {
						goto l61
					}
					if buffer[position] != rune(':') {
						goto l61
					}
					position++
					{
						position65, tokenIndex65 := position, tokenIndex
						if !_rules[ruleRelationName]() {
							goto l65
						}
						{
							position66, tokenIndex66 := position, tokenIndex
							if !_rules[ruleEntityChar]() {
								goto l66
							}
							goto l65
						l66:
							position, tokenIndex = position66, tokenIndex66
						}
						goto l61
					l65:
						position, tokenIndex = position65, tokenIndex65
					}
					{
						position67, tokenIndex67 := position, tokenIndex
						if !_rules[ruleQuoted]() {
							goto l68
						}
						goto l67
					l68:
						position, tokenIndex = position67, tokenIndex67
						if !_rules[ruleEntityChar]() {
							goto l61
						}
					l69:
						{
							position70, tokenIndex70 := position, tokenIndex
							if !_rules[ruleEntityChar]() {
								goto l70
							}
							goto l69
						l70:
							position, tokenIndex = position70, tokenIndex70
						}
					}
				l67:
					begin := position63
					end := position
					text = string(buffer[begin:end])
				}
				if !_rules[ruleAction2]() {
					goto l61
				}
				add(ruleEntityField, position62)
			}
			return true
		l61:
			position, tokenIndex = position61, tokenIndex61
			return false
		},
		/* 12 EntityName <- <(Quoted / (((&('?') '?') | (&('*') '*') | (&('_') '_') | (&('a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g' | 'h' | 'i' | 'j' | 'k' | 'l' | 'm' | 'n' | 'o' | 'p' | 'q' | 'r' | 's' | 't' | 'u' | 'v' | 'w' | 'x' | 'y' | 'z') [a-z]) | (&('A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | 'H' | 'I' | 'J' | 'K' | 'L' | 'M' | 'N' | 'O' | 'P' | 'Q' | 'R' | 'S' | 'T' | 'U' | 'V' | 'W' | 'X' | 'Y' | 'Z') [A-Z])) EntityChar*))> */
		func() bool {
			position71, tokenIndex71 := position, tokenIndex
			{
				position72 := position
				{
					position73, tokenIndex73 := position, tokenIndex
					if !_rules[ruleQuoted]() {
						goto l74
					}
					goto l73
				l74:
					position, tokenIndex = position73, tokenIndex73
					{
						switch buffer[position] {
						case '?':
							if buffer[position] != rune('?') {
								goto l71
							}
							position++
						case '*':
							if buffer[position] != rune('*') {
								goto l71
							}
							position++
						case '_':
							if buffer[position] != rune('_') {
								goto l71
							}
							position++
						case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
							if c := buffer[position]; c < rune('a') || c > rune('z') {
								goto l71
							}
							position++
						default:
							if c := buffer[position]; c < rune('A') || c > rune('Z') {
								goto l71
							}
							position++
						}
					}

				l76:
					{
						position77, tokenIndex77 := position, tokenIndex
						if !_rules[ruleEntityChar]() {
							goto l77
						}
						goto l76
					l77:
						position, tokenIndex = position77, tokenIndex77
					}
				}
			l73:
				add(ruleEntityName, position72)
			}
			return true
		l71:
			position, tokenIndex = position71, tokenIndex71
			return false
		},
		/* 13 EntityChar <- <((&('-') '-') | (&('?') '?') | (&('*') '*') | (&('_') '_') | (&('0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9') [0-9]) | (&('a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g' | 'h' | 'i' | 'j' | 'k' | 'l' | 'm' | 'n' | 'o' | 'p' | 'q' | 'r' | 's' | 't' | 'u' | 'v' | 'w' | 'x' | 'y' | 'z') [a-z]) | (&('A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | 'H' | 'I' | 'J' | 'K' | 'L' | 'M' | 'N' | 'O' | 'P' | 'Q' | 'R' | 'S' | 'T' | 'U' | 'V' | 'W' | 'X' | 'Y' | 'Z') [A-Z]))> */
		func() bool {
			position78, tokenIndex78 := position, tokenIndex
			{
				position79 := position
				{
					switch buffer[position] {
					case '-':
						if buffer[position] != rune('-') {
							goto l78
						}
						position++
					case '?':
						if buffer[position] != rune('?') {
							goto l78
						}
						position++
					case '*':
						if buffer[position] != rune('*') {
							goto l78
						}
						position++
					case '_':
						if buffer[position] != rune('_') {
							goto l78
						}
						position++
					case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
						if c := buffer[position]; c < rune('0') || c > rune('9') {
							goto l78
						}
						position++
					case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
						if c := buffer[position]; c < rune('a') || c > rune('z') {
							goto l78
						}
						position++
					default:
						if c := buffer[position]; c < rune('A') || c > rune('Z') {
							goto l78
						}
						position++
					}
				}

				add(ruleEntityChar, position79)
			}
			return true
		l78:
			position, tokenIndex = position78, tokenIndex78
			return false
		},
		/* 14 RelationName <- <(('i' 'm' 'p' 'l') / ('i' 'n' 'h' 'e' 'r' 'i' 't' 's') / ('m' 'e' 't' 'h' 'o' 'd' 's'))> */
		func() bool {
			position81, tokenIndex81 := position, tokenIndex
			{
				position82 := position
				{
					position83, tokenIndex83 := position, tokenIndex
					if buffer[position] != rune('i') {
						goto l84
					}
					position++
					if buffer[position] != rune('m') {
						goto l84
					}
					position++
					if buffer[position] != rune('p') {
						goto l84
					}
					position++
					if buffer[position] != rune('l') {
						goto l84
					}
					position++
					goto l83
				l84:
					position, tokenIndex = position83, tokenIndex83
					if buffer[position] != rune('i') {
						goto l85
					}
					position++
					if buffer[position] != rune('n') {
						goto l85
					}
					position++
					if buffer[position] != rune('h') {
						goto l85
					}
					position++
					if buffer[position] != rune('e') {
						goto l85
					}
					position++
					if buffer[position] != rune('r') {
						goto l85
					}
					position++
					if buffer[position] != rune('i') {
						goto l85
					}
					position++
					if buffer[position] != rune('t') {
						goto l85
					}
					position++
					if buffer[position] != rune('s') {
						goto l85
					}
					position++
					goto l83
				l85:
					position, tokenIndex = position83, tokenIndex83
					if buffer[position] != rune('m') {
						goto l81
					}
					position++
					if buffer[position] != rune('e') {
						goto l81
					}
					position++
					if buffer[position] != rune('t') {
						goto l81
					}
					position++
					if buffer[position] != rune('h') {
						goto l81
					}
					position++
					if buffer[position] != rune('o') {
						goto l81
					}
					position++
					if buffer[position] != rune('d') {
						goto l81
					}
					position++
					if buffer[position] != rune('s') {
						goto l81
					}
					position++
				}
			l83:
				add(ruleRelationName, position82)
			}
			return true
		l81:
			position, tokenIndex = position81, tokenIndex81
			return false
		},
		/* 15 Symbol <- <(('"' <QuotedText> '"' Action3) / (<(((&('?') '?') | (&('*') '*') | (&('_') '_') | (&('a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g' | 'h' | 'i' | 'j' | 'k' | 'l' | 'm' | 'n' | 'o' | 'p' | 'q' | 'r' | 's' | 't' | 'u' | 'v' | 'w' | 'x' | 'y' | 'z') [a-z]) | (&('A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | 'H' | 'I' | 'J' | 'K' | 'L' | 'M' | 'N' | 'O' | 'P' | 'Q' | 'R' | 'S' | 'T' | 'U' | 'V' | 'W' | 'X' | 'Y' | 'Z') [A-Z])) ((&('-') '-') | (&('?') '?') | (&('*') '*') | (&('/') '/') | (&('.') '.') | (&('_') '_') | (&('0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9') [0-9]) | (&('a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g' | 'h' | 'i' | 'j' | 'k' | 'l' | 'm' | 'n' | 'o' | 'p' | 'q' | 'r' | 's' | 't' | 'u' | 'v' | 'w' | 'x' | 'y' | 'z') [a-z]) | (&('A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | 'H' | 'I' | 'J' | 'K' | 'L' | 'M' | 'N' | 'O' | 'P' | 'Q' | 'R' | 'S' | 'T' | 'U' | 'V' | 'W' | 'X' | 'Y' | 'Z') [A-Z]))*)> Action4))> */
		func() bool {
			position86, tokenIndex86 := position, tokenIndex
			{
				position87 := position
				{
					position88, tokenIndex88 := position, tokenIndex
					if buffer[position] != rune('"') {
						goto l89
					}
					position++
					{
						position90 := position
						if !_rules[ruleQuotedText]() {
							goto l89
						}
						begin := position90
						end := position
						text = string(buffer[begin:end])
					}
					if buffer[position] != rune('"') {
						goto l89
					}
					position++
					if !_rules[ruleAction3]() {
						goto l89
					}
					goto l88
				l89:
					position, tokenIndex = position88, tokenIndex88
					{
						position91 := position
						{
							switch buffer[position] {
							case '?':
								if buffer[position] != rune('?') {
									goto l86
								}
								position++
							case '*':
								if buffer[position] != rune('*') {
									goto l86
								}
								position++
							case '_':
								if buffer[position] != rune('_') {
									goto l86
								}
								position++
							case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
								if c := buffer[position]; c < rune('a') || c > rune('z') {
									goto l86
								}
								position++
							default:
								if c := buffer[position]; c < rune('A') || c > rune('Z') {
									goto l86
								}
								position++
							}
						}

					l93:
						{
							position94, tokenIndex94 := position, tokenIndex
							{
								switch buffer[position] {
								case '-':
									if buffer[position] != rune('-') {
										goto l94
									}
									position++
								case '?':
									if buffer[position] != rune('?') {
										goto l94
									}
									position++
								case '*':
									if buffer[position] != rune('*') {
										goto l94
									}
									position++
								case '/':
									if buffer[position] != rune('/') {
										goto l94
									}
									position++
								case '.':
									if buffer[position] != rune('.') {
										goto l94
									}
									position++
								case '_':
									if buffer[position] != rune('_') {
										goto l94
									}
									position++
								case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
									if c := buffer[position]; c < rune('0') || c > rune('9') {
										goto l94
									}
									position++
								case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
									if c := buffer[position]; c < rune('a') || c > rune('z') {
										goto l94
									}
									position++
								default:
									if c := buffer[position]; c < rune('A') || c > rune('Z') {
										goto l94
									}
									position++
								}
							}

							goto l93
						l94:
							position, tokenIndex = position94, tokenIndex94
						}
						begin := position91
						end := position
						text = string(buffer[begin:end])
					}
					if !_rules[ruleAction4]() {
						goto l86
					}
				}
			l88:
				add(ruleSymbol, position87)
			}
			return true
		l86:
			position, tokenIndex = position86, tokenIndex86
			return false
		},
		/* 16 Quoted <- <('"' QuotedText '"')> */
		func() bool {
			position96, tokenIndex96 := position, tokenIndex
			{
				position97 := position
				if buffer[position] != rune('"') {
					goto l96
				}
				position++
				if !_rules[ruleQuotedText]() {
					goto l96
				}
				if buffer[position] != rune('"') {
					goto l96
				}
				position++
				add(ruleQuoted, position97)
			}
			return true
		l96:
			position, tokenIndex = position96, tokenIndex96
			return false
		},
		/* 17 QuotedText <- <(('\\' .) / (!'"' .))*> */
		func() bool {
			{
				position99 := position
			l100:
				{
					position101, tokenIndex101 := position, tokenIndex
					{
						position102, tokenIndex102 := position, tokenIndex
						if buffer[position] != rune('\\') {
							goto l103
						}
						position++
						if !matchDot() {
							goto l103
						}
						goto l102
					l103:
						position, tokenIndex = position102, tokenIndex102
						{
							position104, tokenIndex104 := position, tokenIndex
							if buffer[position] != rune('"') {
								goto l104
							}
							position++
							goto l101
						l104:
							position, tokenIndex = position104, tokenIndex104
						}
						if !matchDot() {
							goto l101
						}
					}
				l102:
					goto l100
				l101:
					position, tokenIndex = position101, tokenIndex101
				}
				add(ruleQuotedText, position99)
			}
			return true
		},
		/* 18 Relation <- <(Transitive / Implementers / Inheritors / ((&('~') Writes) | (&('=') Definition) | (&('>') Outgoing) | (&('<') Incoming) | (&(':') Methods)))> */
		func() bool {
			position105, tokenIndex105 := position, tokenIndex
			{
				position106 := position
				{
					position107, tokenIndex107 := position, tokenIndex
					if !_rules[ruleTransitive]() {
						goto l108
					}
					goto l107
				l108:
					position, tokenIndex = position107, tokenIndex107
					if !_rules[ruleImplementers]() {
						goto l109
					}
					goto l107
				l109:
					position, tokenIndex = position107, tokenIndex107
					if !_rules[ruleInheritors]() {
						goto l110
					}
					goto l107
				l110:
					position, tokenIndex = position107, tokenIndex107
					{
						switch buffer[position] {
						case '~':
							if !_rules[ruleWrites]() {
								goto l105
							}
						case '=':
							if !_rules[ruleDefinition]() {
								goto l105
							}
						case '>':
							if !_rules[ruleOutgoing]() {
								goto l105
							}
						case '<':
							if !_rules[ruleIncoming]() {
								goto l105
							}
						default:
							if !_rules[ruleMethods]() {
								goto l105
							}
						}
					}

				}
			l107:
				add(ruleRelation, position106)
			}
			return true
		l105:
			position, tokenIndex = position105, tokenIndex105
			return false
		},
		/* 19 Transitive <- <('<' '<' <[0-9]*> Action5)> */
		func() bool {
			position112, tokenIndex112 := position, tokenIndex
			{
				position113 := position
				if buffer[position] != rune('<') {
					goto l112
				}
				position++
				if buffer[position] != rune('<') {
					goto l112
				}
				position++
				{
					position114 := position
				l115:
					{
						position116, tokenIndex116 := position, tokenIndex
						if c := buffer[position]; c < rune('0') || c > rune('9') {
							goto l116
						}
						position++
						goto l115
					l116:
						position, tokenIndex = position116, tokenIndex116
					}
					begin := position114
					end := position
					text = string(buffer[begin:end])
				}
				if !_rules[ruleAction5]() {
					goto l112
				}
				add(ruleTransitive, position113)
			}
			return true
		l112:
			position, tokenIndex = position112, tokenIndex112
			return false
		},
		/* 20 Implementers <- <(':' 'i' 'm' 'p' 'l' Action6)> */
		func() bool {
			position117, tokenIndex117 := position, tokenIndex
			{
				position118 := position
				if buffer[position] != rune(':') {
					goto l117
				}
				position++
				if buffer[position] != rune('i') {
					goto l117
				}
				position++
				if buffer[position] != rune('m') {
					goto l117
				}
				position++
				if buffer[position] != rune('p') {
					goto l117
				}
				position++
				if buffer[position] != rune('l') {
					goto l117
				}
				position++
				if !_rules[ruleAction6]() {
					goto l117
				}
				add(ruleImplementers, position118)
			}
			return true
		l117:
			position, tokenIndex = position117, tokenIndex117
			return false
		},
		/* 21 Inheritors <- <(':' 'i' 'n' 'h' 'e' 'r' 'i' 't' 's' Action7)> */
		func() bool {
			position119, tokenIndex119 := position, tokenIndex
			{
				position120 := position
				if buffer[position] != rune(':') {
					goto l119
				}
				position++
				if buffer[position] != rune('i') {
					goto l119
				}
				position++
				if buffer[position] != rune('n') {
					goto l119
				}
				position++
				if buffer[position] != rune('h') {
					goto l119
				}
				position++
				if buffer[position] != rune('e') {
					goto l119
				}
				position++
				if buffer[position] != rune('r') {
					goto l119
				}
				position++
				if buffer[position] != rune('i') {
					goto l119
				}
				position++
				if buffer[position] != rune('t') {
					goto l119
				}
				position++
				if buffer[position] != rune('s') {
					goto l119
				}
				position++
				if !_rules[ruleAction7]() {
					goto l119
				}
				add(ruleInheritors, position120)
			}
			return true
		l119:
			position, tokenIndex = position119, tokenIndex119
			return false
		},
		/* 22 Methods <- <(':' 'm' 'e' 't' 'h' 'o' 'd' 's' Action8)> */
		func() bool {
			position121, tokenIndex121 := position, tokenIndex
			{
				position122 := position
				if buffer[position] != rune(':') {
					goto l121
				}
				position++
				if buffer[position] != rune('m') {
					goto l121
				}
				position++
				if buffer[position] != rune('e') {
					goto l121
				}
				position++
				if buffer[position] != rune('t') {
					goto l121
				}
				position++
				if buffer[position] != rune('h') {
					goto l121
				}
				position++
				if buffer[position] != rune('o') {
					goto l121
				}
				position++
				if buffer[position] != rune('d') {
					goto l121
				}
				position++
				if buffer[position] != rune('s') {
					goto l121
				}
				position++
				if !_rules[ruleAction8]() {
					goto l121
				}
				add(ruleMethods, position122)
			}
			return true
		l121:
			position, tokenIndex = position121, tokenIndex121
			return false
		},
		/* 23 Incoming <- <('<' Action9)> */
		func() bool {
			position123, tokenIndex123 := position, tokenIndex
			{
				position124 := position
				if buffer[position] != rune('<') {
					goto l123
				}
				position++
				if !_rules[ruleAction9]() {
					goto l123
				}
				add(ruleIncoming, position124)
			}
			return true
		l123:
			position, tokenIndex = position123, tokenIndex123
			return false
		},
		/* 24 Outgoing <- <('>' Action10)> */
		func() bool {
			position125, tokenIndex125 := position, tokenIndex
			{
				position126 := position
				if buffer[position] != rune('>') {
					goto l125
				}
				position++
				if !_rules[ruleAction10]() {
					goto l125
				}
				add(ruleOutgoing, position126)
			}
			return true
		l125:
			position, tokenIndex = position125, tokenIndex125
			return false
		},
		/* 25 Definition <- <('=' Action11)> */
		func() bool {
			position127, tokenIndex127 := position, tokenIndex
			{
				position128 := position
				if buffer[position] != rune('=') {
					goto l127
				}
				position++
				if !_rules[ruleAction11]() {
					goto l127
				}
				add(ruleDefinition, position128)
			}
			return true
		l127:
			position, tokenIndex = position127, tokenIndex127
			return false
		},
		/* 26 Writes <- <('~' 'w' Action12)> */
		func() bool {
			position129, tokenIndex129 := position, tokenIndex
			{
				position130 := position
				if buffer[position] != rune('~') {
					goto l129
				}
				position++
				if buffer[position] != rune('w') {
					goto l129
				}
				position++
				if !_rules[ruleAction12]() {
					goto l129
				}
				add(ruleWrites, position130)
			}
			return true
		l129:
			position, tokenIndex = position129, tokenIndex129
			return false
		},
		/* 27 Filter <- <(RoleFilter / ValueFilter)> */
		func() bool {
			position131, tokenIndex131 := position, tokenIndex
			{
				position132 := position
				{
					position133, tokenIndex133 := position, tokenIndex
					if !_rules[ruleRoleFilter]() {
						goto l134
					}
					goto l133
				l134:
					position, tokenIndex = position133, tokenIndex133
					if !_rules[ruleValueFilter]() {
						goto l131
					}
				}
			l133:
				add(ruleFilter, position132)
			}
			return true
		l131:
			position, tokenIndex = position131, tokenIndex131
			return false
		},
		/* 28 RoleFilter <- <(<('~' 'w')> Action13)> */
		func() bool {
			position135, tokenIndex135 := position, tokenIndex
			{
				position136 := position
				{
					position137 := position
					if buffer[position] != rune('~') {
						goto l135
					}
					position++
					if buffer[position] != rune('w') {
						goto l135
					}
					position++
					begin := position137
					end := position
					text = string(buffer[begin:end])
				}
				if !_rules[ruleAction13]() {
					goto l135
				}
				add(ruleRoleFilter, position136)
			}
			return true
		l135:
			position, tokenIndex = position135, tokenIndex135
			return false
		},
		/* 29 ValueFilter <- <(<(('-' 'f') / ('+' 'p' 'k' 'g') / ('-' 'p' 'k' 'g'))> Action14 Spacing Value)> */
		func() bool {
			position138, tokenIndex138 := position, tokenIndex
			{
				position139 := position
				{
					position140 := position
					{
						position141, tokenIndex141 := position, tokenIndex
						if buffer[position] != rune('-') {
							goto l142
						}
						position++
						if buffer[position] != rune('f') {
							goto l142
						}
						position++
						goto l141
					l142:
						position, tokenIndex = position141, tokenIndex141
						if buffer[position] != rune('+') {
							goto l143
						}
						position++
						if buffer[position] != rune('p') {
							goto l143
						}
						position++
						if buffer[position] != rune('k') {
							goto l143
						}
						position++
						if buffer[position] != rune('g') {
							goto l143
						}
						position++
						goto l141
					l143:
						position, tokenIndex = position141, tokenIndex141
						if buffer[position] != rune('-') {
							goto l138
						}
						position++
						if buffer[position] != rune('p') {
							goto l138
						}
						position++
						if buffer[position] != rune('k') {
							goto l138
						}
						position++
						if buffer[position] != rune('g') {
							goto l138
						}
						position++
					}
				l141:
					begin := position140
					end := position
					text = string(buffer[begin:end])
				}
				if !_rules[ruleAction14]() {
					goto l138
				}
				if !_rules[ruleSpacing]() {
					goto l138
				}
				if !_rules[ruleValue]() {
					goto l138
				}
				add(ruleValueFilter, position139)
			}
			return true
		l138:
			position, tokenIndex = position138, tokenIndex138
			return false
		},
		/* 30 Value <- <(<((&('-') '-') | (&('*') '*') | (&('/') '/') | (&('.') '.') | (&('_') '_') | (&('0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9') [0-9]) | (&('a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g' | 'h' | 'i' | 'j' | 'k' | 'l' | 'm' | 'n' | 'o' | 'p' | 'q' | 'r' | 's' | 't' | 'u' | 'v' | 'w' | 'x' | 'y' | 'z') [a-z]) | (&('A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | 'H' | 'I' | 'J' | 'K' | 'L' | 'M' | 'N' | 'O' | 'P' | 'Q' | 'R' | 'S' | 'T' | 'U' | 'V' | 'W' | 'X' | 'Y' | 'Z') [A-Z]))+> Action15)> */
		func() bool {
			position144, tokenIndex144 := position, tokenIndex
			{
				position145 := position
				{
					position146 := position
					{
						switch buffer[position] {
						case '-':
							if buffer[position] != rune('-') {
								goto l144
							}
							position++
						case '*':
							if buffer[position] != rune('*') {
								goto l144
							}
							position++
						case '/':
							if buffer[position] != rune('/') {
								goto l144
							}
							position++
						case '.':
							if buffer[position] != rune('.') {
								goto l144
							}
							position++
						case '_':
							if buffer[position] != rune('_') {
								goto l144
							}
							position++
						case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
							if c := buffer[position]; c < rune('0') || c > rune('9') {
								goto l144
							}
							position++
						case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
							if c := buffer[position]; c < rune('a') || c > rune('z') {
								goto l144
							}
							position++
						default:
							if c := buffer[position]; c < rune('A') || c > rune('Z') {
								goto l144
							}
							position++
						}
					}

				l147:
					{
						position148, tokenIndex148 := position, tokenIndex
						{
							switch buffer[position] {
							case '-':
								if buffer[position] != rune('-') {
									goto l148
								}
								position++
							case '*':
								if buffer[position] != rune('*') {
									goto l148
								}
								position++
							case '/':
								if buffer[position] != rune('/') {
									goto l148
								}
								position++
							case '.':
								if buffer[position] != rune('.') {
									goto l148
								}
								position++
							case '_':
								if buffer[position] != rune('_') {
									goto l148
								}
								position++
							case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
								if c := buffer[position]; c < rune('0') || c > rune('9') {
									goto l148
								}
								position++
							case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
								if c := buffer[position]; c < rune('a') || c > rune('z') {
									goto l148
								}
								position++
							default:
								if c := buffer[position]; c < rune('A') || c > rune('Z') {
									goto l148
								}
								position++
							}
						}

						goto l147
					l148:
						position, tokenIndex = position148, tokenIndex148
					}
					begin := position146
					end := position
					text = string(buffer[begin:end])
				}
				if !_rules[ruleAction15]() {
					goto l144
				}
				add(ruleValue, position145)
			}
			return true
		l144:
			position, tokenIndex = position144, tokenIndex144
			return false
		},
		/* 31 PathStep <- <(PathOperator _ Primary)> */
		func() bool {
			position151, tokenIndex151 := position, tokenIndex
			{
				position152 := position
				if !_rules[rulePathOperator]() {
					goto l151
				}
				if !_rules[rule_]() {
					goto l151
				}
				if !_rules[rulePrimary]() {
					goto l151
				}
				add(rulePathStep, position152)
			}
			return true
		l151:
			position, tokenIndex = position151, tokenIndex151
			return false
		},
		/* 32 PathOperator <- <('>' '>' <[0-9]*> Action16)> */
		func() bool {
			position153, tokenIndex153 := position, tokenIndex
			{
				position154 := position
				if buffer[position] != rune('>') {
					goto l153
				}
				position++
				if buffer[position] != rune('>') {
					goto l153
				}
				position++
				{
					position155 := position
				l156:
					{
						position157, tokenIndex157 := position, tokenIndex
						if c := buffer[position]; c < rune('0') || c > rune('9') {
							goto l157
						}
						position++
						goto l156
					l157:
						position, tokenIndex = position157, tokenIndex157
					}
					begin := position155
					end := position
					text = string(buffer[begin:end])
				}
				if !_rules[ruleAction16]() {
					goto l153
				}
				add(rulePathOperator, position154)
			}
			return true
		l153:
			position, tokenIndex = position153, tokenIndex153
			return false
		},
		/* 33 UnionOperator <- <('|' Action17)> */
		func() bool {
			position158, tokenIndex158 := position, tokenIndex
			{
				position159 := position
				if buffer[position] != rune('|') {
					goto l158
				}
				position++
				if !_rules[ruleAction17]() {
					goto l158
				}
				add(ruleUnionOperator, position159)
			}
			return true
		l158:
			position, tokenIndex = position158, tokenIndex158
			return false
		},
		/* 34 IntersectionOperator <- <('&' Action18)> */
		func() bool {
			position160, tokenIndex160 := position, tokenIndex
			{
				position161 := position
				if buffer[position] != rune('&') {
					goto l160
				}
				position++
				if !_rules[ruleAction18]() {
					goto l160
				}
				add(ruleIntersectionOperator, position161)
			}
			return true
		l160:
			position, tokenIndex = position160, tokenIndex160
			return false
		},
		/* 35 Open <- <('(' Action19)> */
		func() bool {
			position162, tokenIndex162 := position, tokenIndex
			{
				position163 := position
				if buffer[position] != rune('(') {
					goto l162
				}
				position++
				if !_rules[ruleAction19]() {
					goto l162
				}
				add(ruleOpen, position163)
			}
			return true
		l162:
			position, tokenIndex = position162, tokenIndex162
			return false
		},
		/* 36 Close <- <(')' Action20)> */
		func() bool {
			position164, tokenIndex164 := position, tokenIndex
			{
				position165 := position
				if buffer[position] != rune(')') {
					goto l164
				}
				position++
				if !_rules[ruleAction20]() {
					goto l164
				}
				add(ruleClose, position165)
			}
			return true
		l164:
			position, tokenIndex = position164, tokenIndex164
			return false
		},
		/* 37 Spacing <- <((&('\n') '\n') | (&('\r') '\r') | (&('\t') '\t') | (&(' ') ' '))+> */
		func() bool {
			position166, tokenIndex166 := position, tokenIndex
			{
				position167 := position
				{
					switch buffer[position] {
					case '\n':
						if buffer[position] != rune('\n') {
							goto l166
						}
						position++
					case '\r':
						if buffer[position] != rune('\r') {
							goto l166
						}
						position++
					case '\t':
						if buffer[position] != rune('\t') {
							goto l166
						}
						position++
					default:
						if buffer[position] != rune(' ') {
							goto l166
						}
						position++
					}
				}

			l168:
				{
					position169, tokenIndex169 := position, tokenIndex
					{
						switch buffer[position] {
						case '\n':
							if buffer[position] != rune('\n') {
								goto l169
							}
							position++
						case '\r':
							if buffer[position] != rune('\r') {
								goto l169
							}
							position++
						case '\t':
							if buffer[position] != rune('\t') {
								goto l169
							}
							position++
						default:
							if buffer[position] != rune(' ') {
								goto l169
							}
							position++
						}
					}

					goto l168
				l169:
					position, tokenIndex = position169, tokenIndex169
				}
				add(ruleSpacing, position167)
			}
			return true
		l166:
			position, tokenIndex = position166, tokenIndex166
			return false
		},
		/* 38 _ <- <((&('\n') '\n') | (&('\r') '\r') | (&('\t') '\t') | (&(' ') ' '))*> */
		func() bool {
			{
				position173 := position
			l174:
				{
					position175, tokenIndex175 := position, tokenIndex
					{
						switch buffer[position] {
						case '\n':
							if buffer[position] != rune('\n') {
								goto l175
							}
							position++
						case '\r':
							if buffer[position] != rune('\r') {
								goto l175
							}
							position++
						case '\t':
							if buffer[position] != rune('\t') {
								goto l175
							}
							position++
						default:
							if buffer[position] != rune(' ') {
								goto l175
							}
							position++
						}
					}

					goto l174
				l175:
					position, tokenIndex = position175, tokenIndex175
				}
				add(rule_, position173)
			}
			return true
		},
		nil,
		/* 41 Action0 <- <{ p.addToken("selector", text) }> */
		func() bool {
			{
				p.addToken("selector", text)
			}
			return true
		},
		/* 42 Action1 <- <{ p.addToken("modifier", text) }> */
		func() bool {
			{
				p.addToken("modifier", text)
			}
			return true
		},
		/* 43 Action2 <- <{ p.addToken("entity_field", text) }> */
		func() bool {
			{
				p.addToken("entity_field", text)
			}
			return true
		},
		/* 44 Action3 <- <{ p.addToken("symbol", text) }> */
		func() bool {
			{
				p.addToken("symbol", text)
			}
			return true
		},
		/* 45 Action4 <- <{ p.addToken("symbol", text) }> */
		func() bool {
			{
				p.addToken("symbol", text)
			}
			return true
		},
		/* 46 Action5 <- <{ p.addToken("relation", "<<" + text) }> */
		func() bool {
			{
				p.addToken("relation", "<<"+text)
			}
			return true
		},
		/* 47 Action6 <- <{ p.addToken("relation", ":impl") }> */
		func() bool {
			{
				p.addToken("relation", ":impl")
			}
			return true
		},
		/* 48 Action7 <- <{ p.addToken("relation", ":inherits") }> */
		func() bool {
			{
				p.addToken("relation", ":inherits")
			}
			return true
		},
		/* 49 Action8 <- <{ p.addToken("relation", ":methods") }> */
		func() bool {
			{
				p.addToken("relation", ":methods")
			}
			return true
		},
		/* 50 Action9 <- <{ p.addToken("relation", "<") }> */
		func() bool {
			{
				p.addToken("relation", "<")
			}
			return true
		},
		/* 51 Action10 <- <{ p.addToken("relation", ">") }> */
		func() bool {
			{
				p.addToken("relation", ">")
			}
			return true
		},
		/* 52 Action11 <- <{ p.addToken("relation", "=") }> */
		func() bool {
			{
				p.addToken("relation", "=")
			}
			return true
		},
		/* 53 Action12 <- <{ p.addToken("relation", "~w") }> */
		func() bool {
			{
				p.addToken("relation", "~w")
			}
			return true
		},
		/* 54 Action13 <- <{ p.addToken("filter", text) }> */
		func() bool {
			{
				p.addToken("filter", text)
			}
			return true
		},
		/* 55 Action14 <- <{ p.addToken("filter", text) }> */
		func() bool {
			{
				p.addToken("filter", text)
			}
			return true
		},
		/* 56 Action15 <- <{ p.addToken("value", text) }> */
		func() bool {
			{
				p.addToken("value", text)
			}
			return true
		},
		/* 57 Action16 <- <{ p.addToken("path", ">>" + text) }> */
		func() bool {
			{
				p.addToken("path", ">>"+text)
			}
			return true
		},
		/* 58 Action17 <- <{ p.addToken("or", "|") }> */
		func() bool {
			{
				p.addToken("or", "|")
			}
			return true
		},
		/* 59 Action18 <- <{ p.addToken("and", "&") }> */
		func() bool {
			{
				p.addToken("and", "&")
			}
			return true
		},
		/* 60 Action19 <- <{ p.addToken("open", "(") }> */
		func() bool {
			{
				p.addToken("open", "(")
			}
			return true
		},
		/* 61 Action20 <- <{ p.addToken("close", ")") }> */
		func() bool {
			{
				p.addToken("close", ")")
			}
			return true
		},
	}
	p.rules = _rules
	return nil
}
