// Code generated by go tool peg -noast -switch grammar.peg; DO NOT EDIT.

package query

import (
	"fmt"
	"sort"
	"strconv"
)

const endSymbol rune = 1114112

/* The rule types inferred from the grammar are below. */
type pegRule uint8

const (
	ruleUnknown pegRule = iota
	ruleQuery
	ruleSet
	ruleIntersection
	ruleChain
	rulePrimary
	ruleStep
	ruleSelector
	ruleModifier
	ruleSelectorText
	ruleSelectorValue
	ruleSymbol
	ruleRelation
	ruleTransitive
	ruleImplementers
	ruleInheritors
	ruleMethods
	ruleIncoming
	ruleOutgoing
	ruleDefinition
	ruleWrites
	ruleFilter
	ruleRoleFilter
	ruleValueFilter
	ruleValue
	rulePathStep
	rulePathOperator
	ruleUnionOperator
	ruleIntersectionOperator
	ruleOpen
	ruleClose
	ruleSpacing
	rule_
	rulePegText
	ruleAction0
	ruleAction1
	ruleAction2
	ruleAction3
	ruleAction4
	ruleAction5
	ruleAction6
	ruleAction7
	ruleAction8
	ruleAction9
	ruleAction10
	ruleAction11
	ruleAction12
	ruleAction13
	ruleAction14
	ruleAction15
	ruleAction16
	ruleAction17
	ruleAction18
)

var rul3s = [...]string{
	"Unknown",
	"Query",
	"Set",
	"Intersection",
	"Chain",
	"Primary",
	"Step",
	"Selector",
	"Modifier",
	"SelectorText",
	"SelectorValue",
	"Symbol",
	"Relation",
	"Transitive",
	"Implementers",
	"Inheritors",
	"Methods",
	"Incoming",
	"Outgoing",
	"Definition",
	"Writes",
	"Filter",
	"RoleFilter",
	"ValueFilter",
	"Value",
	"PathStep",
	"PathOperator",
	"UnionOperator",
	"IntersectionOperator",
	"Open",
	"Close",
	"Spacing",
	"_",
	"PegText",
	"Action0",
	"Action1",
	"Action2",
	"Action3",
	"Action4",
	"Action5",
	"Action6",
	"Action7",
	"Action8",
	"Action9",
	"Action10",
	"Action11",
	"Action12",
	"Action13",
	"Action14",
	"Action15",
	"Action16",
	"Action17",
	"Action18",
}

type token32 struct {
	pegRule
	begin, end uint32
}

func (t *token32) String() string {
	return fmt.Sprintf("\x1B[34m%v\x1B[m %v %v", rul3s[t.pegRule], t.begin, t.end)
}

type queryGrammar struct {
	parserState

	Buffer string
	buffer []rune
	rules  [53]func() bool
	parse  func(rule ...int) error
	reset  func()
	Pretty bool
}

func (p *queryGrammar) Parse(rule ...int) error {
	return p.parse(rule...)
}

func (p *queryGrammar) Reset() {
	p.reset()
}

type textPosition struct {
	line, symbol int
}

type textPositionMap map[int]textPosition

func translatePositions(buffer []rune, positions []int) textPositionMap {
	length, translations, j, line, symbol := len(positions), make(textPositionMap, len(positions)), 0, 1, 0
	sort.Ints(positions)

search:
	for i, c := range buffer {
		if c == '\n' {
			line, symbol = line+1, 0
		} else {
			symbol++
		}
		if i == positions[j] {
			translations[positions[j]] = textPosition{line, symbol}
			for j++; j < length; j++ {
				if i != positions[j] {
					continue search
				}
			}
			break search
		}
	}

	return translations
}

type parseError struct {
	p   *queryGrammar
	max token32
}

func (e *parseError) Error() string {
	tokens, err := []token32{e.max}, "\n"
	positions, p := make([]int, 2*len(tokens)), 0
	for _, token := range tokens {
		positions[p], p = int(token.begin), p+1
		positions[p], p = int(token.end), p+1
	}
	translations := translatePositions(e.p.buffer, positions)
	format := "parse error near %v (line %v symbol %v - line %v symbol %v):\n%v\n"
	if e.p.Pretty {
		format = "parse error near \x1B[34m%v\x1B[m (line %v symbol %v - line %v symbol %v):\n%v\n"
	}
	for _, token := range tokens {
		begin, end := int(token.begin), int(token.end)
		err += fmt.Sprintf(format,
			rul3s[token.pegRule],
			translations[begin].line, translations[begin].symbol,
			translations[end].line, translations[end].symbol,
			strconv.Quote(string(e.p.buffer[begin:end])))
	}

	return err
}

func Pretty(pretty bool) func(*queryGrammar) error {
	return func(p *queryGrammar) error {
		p.Pretty = pretty
		return nil
	}
}

func (p *queryGrammar) Init(options ...func(*queryGrammar) error) error {
	var (
		max                  token32
		position, tokenIndex uint32
		buffer               []rune
		text                 string
	)
	for _, option := range options {
		err := option(p)
		if err != nil {
			return err
		}
	}
	p.reset = func() {
		max = token32{}
		position, tokenIndex = 0, 0

		p.buffer = []rune(p.Buffer)
		if len(p.buffer) == 0 || p.buffer[len(p.buffer)-1] != endSymbol {
			p.buffer = append(p.buffer, endSymbol)
		}
		buffer = p.buffer
	}
	p.reset()

	_rules := p.rules
	p.parse = func(rule ...int) error {
		r := 1
		if len(rule) > 0 {
			r = rule[0]
		}
		matches := p.rules[r]()
		if matches {
			return nil
		}
		return &parseError{p, max}
	}

	add := func(rule pegRule, begin uint32) {
		tokenIndex++
		if begin != position && position > max.end {
			max = token32{rule, begin, position}
		}
	}

	matchDot := func() bool {
		if buffer[position] != endSymbol {
			position++
			return true
		}
		return false
	}

	/*matchChar := func(c byte) bool {
		if buffer[position] == c {
			position++
			return true
		}
		return false
	}*/

	/*matchRange := func(lower byte, upper byte) bool {
		if c := buffer[position]; c >= lower && c <= upper {
			position++
			return true
		}
		return false
	}*/

	_rules = [...]func() bool{
		nil,
		/* 0 Query <- <(_ Set _ !.)> */
		func() bool {
			position0, tokenIndex0 := position, tokenIndex
			{
				position1 := position
				if !_rules[rule_]() {
					goto l0
				}
				if !_rules[ruleSet]() {
					goto l0
				}
				if !_rules[rule_]() {
					goto l0
				}
				{
					position2, tokenIndex2 := position, tokenIndex
					if !matchDot() {
						goto l2
					}
					goto l0
				l2:
					position, tokenIndex = position2, tokenIndex2
				}
				add(ruleQuery, position1)
			}
			return true
		l0:
			position, tokenIndex = position0, tokenIndex0
			return false
		},
		/* 1 Set <- <(Intersection (_ UnionOperator _ Intersection)*)> */
		func() bool {
			position3, tokenIndex3 := position, tokenIndex
			{
				position4 := position
				if !_rules[ruleIntersection]() {
					goto l3
				}
			l5:
				{
					position6, tokenIndex6 := position, tokenIndex
					if !_rules[rule_]() {
						goto l6
					}
					if !_rules[ruleUnionOperator]() {
						goto l6
					}
					if !_rules[rule_]() {
						goto l6
					}
					if !_rules[ruleIntersection]() {
						goto l6
					}
					goto l5
				l6:
					position, tokenIndex = position6, tokenIndex6
				}
				add(ruleSet, position4)
			}
			return true
		l3:
			position, tokenIndex = position3, tokenIndex3
			return false
		},
		/* 2 Intersection <- <(Chain (_ IntersectionOperator _ Chain)*)> */
		func() bool {
			position7, tokenIndex7 := position, tokenIndex
			{
				position8 := position
				if !_rules[ruleChain]() {
					goto l7
				}
			l9:
				{
					position10, tokenIndex10 := position, tokenIndex
					if !_rules[rule_]() {
						goto l10
					}
					if !_rules[ruleIntersectionOperator]() {
						goto l10
					}
					if !_rules[rule_]() {
						goto l10
					}
					if !_rules[ruleChain]() {
						goto l10
					}
					goto l9
				l10:
					position, tokenIndex = position10, tokenIndex10
				}
				add(ruleIntersection, position8)
			}
			return true
		l7:
			position, tokenIndex = position7, tokenIndex7
			return false
		},
		/* 3 Chain <- <(Primary (_ (PathStep / Step / Modifier))*)> */
		func() bool {
			position11, tokenIndex11 := position, tokenIndex
			{
				position12 := position
				if !_rules[rulePrimary]() {
					goto l11
				}
			l13:
				{
					position14, tokenIndex14 := position, tokenIndex
					if !_rules[rule_]() {
						goto l14
					}
					{
						position15, tokenIndex15 := position, tokenIndex
						if !_rules[rulePathStep]() {
							goto l16
						}
						goto l15
					l16:
						position, tokenIndex = position15, tokenIndex15
						if !_rules[ruleStep]() {
							goto l17
						}
						goto l15
					l17:
						position, tokenIndex = position15, tokenIndex15
						if !_rules[ruleModifier]() {
							goto l14
						}
					}
				l15:
					goto l13
				l14:
					position, tokenIndex = position14, tokenIndex14
				}
				add(ruleChain, position12)
			}
			return true
		l11:
			position, tokenIndex = position11, tokenIndex11
			return false
		},
		/* 4 Primary <- <(Selector / Symbol / (Open _ Set _ Close))> */
		func() bool {
			position18, tokenIndex18 := position, tokenIndex
			{
				position19 := position
				{
					position20, tokenIndex20 := position, tokenIndex
					if !_rules[ruleSelector]() {
						goto l21
					}
					goto l20
				l21:
					position, tokenIndex = position20, tokenIndex20
					if !_rules[ruleSymbol]() {
						goto l22
					}
					goto l20
				l22:
					position, tokenIndex = position20, tokenIndex20
					if !_rules[ruleOpen]() {
						goto l18
					}
					if !_rules[rule_]() {
						goto l18
					}
					if !_rules[ruleSet]() {
						goto l18
					}
					if !_rules[rule_]() {
						goto l18
					}
					if !_rules[ruleClose]() {
						goto l18
					}
				}
			l20:
				add(rulePrimary, position19)
			}
			return true
		l18:
			position, tokenIndex = position18, tokenIndex18
			return false
		},
		/* 5 Step <- <(Relation (_ Filter)* (_ Primary (_ Modifier)*)?)> */
		func() bool {
			position23, tokenIndex23 := position, tokenIndex
			{
				position24 := position
				if !_rules[ruleRelation]() {
					goto l23
				}
			l25:
				{
					position26, tokenIndex26 := position, tokenIndex
					if !_rules[rule_]() {
						goto l26
					}
					if !_rules[ruleFilter]() {
						goto l26
					}
					goto l25
				l26:
					position, tokenIndex = position26, tokenIndex26
				}
				{
					position27, tokenIndex27 := position, tokenIndex
					if !_rules[rule_]() {
						goto l27
					}
					if !_rules[rulePrimary]() {
						goto l27
					}
				l29:
					{
						position30, tokenIndex30 := position, tokenIndex
						if !_rules[rule_]() {
							goto l30
						}
						if !_rules[ruleModifier]() {
							goto l30
						}
						goto l29
					l30:
						position, tokenIndex = position30, tokenIndex30
					}
					goto l28
				l27:
					position, tokenIndex = position27, tokenIndex27
				}
			l28:
				add(ruleStep, position24)
			}
			return true
		l23:
			position, tokenIndex = position23, tokenIndex23
			return false
		},
		/* 6 Selector <- <(<SelectorText> Action0)> */
		func() bool {
			position31, tokenIndex31 := position, tokenIndex
			{
				position32 := position
				{
					position33 := position
					if !_rules[ruleSelectorText]() {
						goto l31
					}
					begin := position33
					end := position
					text = string(buffer[begin:end])
				}
				if !_rules[ruleAction0]() {
					goto l31
				}
				add(ruleSelector, position32)
			}
			return true
		l31:
			position, tokenIndex = position31, tokenIndex31
			return false
		},
		/* 7 Modifier <- <(<(('+' / '-') SelectorText)> Action1)> */
		func() bool {
			position34, tokenIndex34 := position, tokenIndex
			{
				position35 := position
				{
					position36 := position
					{
						position37, tokenIndex37 := position, tokenIndex
						if buffer[position] != rune('+') {
							goto l38
						}
						position++
						goto l37
					l38:
						position, tokenIndex = position37, tokenIndex37
						if buffer[position] != rune('-') {
							goto l34
						}
						position++
					}
				l37:
					if !_rules[ruleSelectorText]() {
						goto l34
					}
					begin := position36
					end := position
					text = string(buffer[begin:end])
				}
				if !_rules[ruleAction1]() {
					goto l34
				}
				add(ruleModifier, position35)
			}
			return true
		l34:
			position, tokenIndex = position34, tokenIndex34
			return false
		},
		/* 8 SelectorText <- <((('p' 'a' 'c' 'k' 'a' 'g' 'e') / ('m' 'o' 'd' 'u' 'l' 'e') / ('m' 'e' 't' 'h' 'o' 'd') / ('f' 'i' 'e' 'l' 'd') / ('p' 'a' 't' 'h') / ((&('m') ('m' 'o' 'd')) | (&('p') ('p' 'k' 'g')) | (&('v') ('v' 'a' 'r')) | (&('a') ('a' 'l' 'l')) | (&('t') ('t' 'y' 'p' 'e')) | (&('f') ('f' 'u' 'n' 'c')) | (&('s') ('s' 't' 'r' 'u' 'c' 't')))) ':' SelectorValue (':' SelectorValue)?)> */
		func() bool {
			position39, tokenIndex39 := position, tokenIndex
			{
				position40 := position
				{
					position41, tokenIndex41 := position, tokenIndex
					if buffer[position] != rune('p') {
						goto l42
					}
					position++
					if buffer[position] != rune('a') {
						goto l42
					}
					position++
					if buffer[position] != rune('c') {
						goto l42
					}
					position++
					if buffer[position] != rune('k') {
						goto l42
					}
					position++
					if buffer[position] != rune('a') {
						goto l42
					}
					position++
					if buffer[position] != rune('g') {
						goto l42
					}
					position++
					if buffer[position] != rune('e') {
						goto l42
					}
					position++
					goto l41
				l42:
					position, tokenIndex = position41, tokenIndex41
					if buffer[position] != rune('m') {
						goto l43
					}
					position++
					if buffer[position] != rune('o') {
						goto l43
					}
					position++
					if buffer[position] != rune('d') {
						goto l43
					}
					position++
					if buffer[position] != rune('u') {
						goto l43
					}
					position++
					if buffer[position] != rune('l') {
						goto l43
					}
					position++
					if buffer[position] != rune('e') {
						goto l43
					}
					position++
					goto l41
				l43:
					position, tokenIndex = position41, tokenIndex41
					if buffer[position] != rune('m') {
						goto l44
					}
					position++
					if buffer[position] != rune('e') {
						goto l44
					}
					position++
					if buffer[position] != rune('t') {
						goto l44
					}
					position++
					if buffer[position] != rune('h') {
						goto l44
					}
					position++
					if buffer[position] != rune('o') {
						goto l44
					}
					position++
					if buffer[position] != rune('d') {
						goto l44
					}
					position++
					goto l41
				l44:
					position, tokenIndex = position41, tokenIndex41
					if buffer[position] != rune('f') {
						goto l45
					}
					position++
					if buffer[position] != rune('i') {
						goto l45
					}
					position++
					if buffer[position] != rune('e') {
						goto l45
					}
					position++
					if buffer[position] != rune('l') {
						goto l45
					}
					position++
					if buffer[position] != rune('d') {
						goto l45
					}
					position++
					goto l41
				l45:
					position, tokenIndex = position41, tokenIndex41
					if buffer[position] != rune('p') {
						goto l46
					}
					position++
					if buffer[position] != rune('a') {
						goto l46
					}
					position++
					if buffer[position] != rune('t') {
						goto l46
					}
					position++
					if buffer[position] != rune('h') {
						goto l46
					}
					position++
					goto l41
				l46:
					position, tokenIndex = position41, tokenIndex41
					{
						switch buffer[position] {
						case 'm':
							if buffer[position] != rune('m') {
								goto l39
							}
							position++
							if buffer[position] != rune('o') {
								goto l39
							}
							position++
							if buffer[position] != rune('d') {
								goto l39
							}
							position++
						case 'p':
							if buffer[position] != rune('p') {
								goto l39
							}
							position++
							if buffer[position] != rune('k') {
								goto l39
							}
							position++
							if buffer[position] != rune('g') {
								goto l39
							}
							position++
						case 'v':
							if buffer[position] != rune('v') {
								goto l39
							}
							position++
							if buffer[position] != rune('a') {
								goto l39
							}
							position++
							if buffer[position] != rune('r') {
								goto l39
							}
							position++
						case 'a':
							if buffer[position] != rune('a') {
								goto l39
							}
							position++
							if buffer[position] != rune('l') {
								goto l39
							}
							position++
							if buffer[position] != rune('l') {
								goto l39
							}
							position++
						case 't':
							if buffer[position] != rune('t') {
								goto l39
							}
							position++
							if buffer[position] != rune('y') {
								goto l39
							}
							position++
							if buffer[position] != rune('p') {
								goto l39
							}
							position++
							if buffer[position] != rune('e') {
								goto l39
							}
							position++
						case 'f':
							if buffer[position] != rune('f') {
								goto l39
							}
							position++
							if buffer[position] != rune('u') {
								goto l39
							}
							position++
							if buffer[position] != rune('n') {
								goto l39
							}
							position++
							if buffer[position] != rune('c') {
								goto l39
							}
							position++
						default:
							if buffer[position] != rune('s') {
								goto l39
							}
							position++
							if buffer[position] != rune('t') {
								goto l39
							}
							position++
							if buffer[position] != rune('r') {
								goto l39
							}
							position++
							if buffer[position] != rune('u') {
								goto l39
							}
							position++
							if buffer[position] != rune('c') {
								goto l39
							}
							position++
							if buffer[position] != rune('t') {
								goto l39
							}
							position++
						}
					}

				}
			l41:
				if buffer[position] != rune(':') {
					goto l39
				}
				position++
				if !_rules[ruleSelectorValue]() {
					goto l39
				}
				{
					position48, tokenIndex48 := position, tokenIndex
					if buffer[position] != rune(':') {
						goto l48
					}
					position++
					if !_rules[ruleSelectorValue]() {
						goto l48
					}
					goto l49
				l48:
					position, tokenIndex = position48, tokenIndex48
				}
			l49:
				add(ruleSelectorText, position40)
			}
			return true
		l39:
			position, tokenIndex = position39, tokenIndex39
			return false
		},
		/* 9 SelectorValue <- <((&('\\') ('\\' .)) | (&('-') '-') | (&('!') '!') | (&('$') '$') | (&('#') '#') | (&('@') '@') | (&('?') '?') | (&('*') '*') | (&('/') '/') | (&('.') '.') | (&('_') '_') | (&('0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9') [0-9]) | (&('a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g' | 'h' | 'i' | 'j' | 'k' | 'l' | 'm' | 'n' | 'o' | 'p' | 'q' | 'r' | 's' | 't' | 'u' | 'v' | 'w' | 'x' | 'y' | 'z') [a-z]) | (&('A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | 'H' | 'I' | 'J' | 'K' | 'L' | 'M' | 'N' | 'O' | 'P' | 'Q' | 'R' | 'S' | 'T' | 'U' | 'V' | 'W' | 'X' | 'Y' | 'Z') [A-Z]))+> */
		func() bool {
			position50, tokenIndex50 := position, tokenIndex
			{
				position51 := position
				{
					switch buffer[position] {
					case '\\':
						if buffer[position] != rune('\\') {
							goto l50
						}
						position++
						if !matchDot() {
							goto l50
						}
					case '-':
						if buffer[position] != rune('-') {
							goto l50
						}
						position++
					case '!':
						if buffer[position] != rune('!') {
							goto l50
						}
						position++
					case '$':
						if buffer[position] != rune('$') {
							goto l50
						}
						position++
					case '#':
						if buffer[position] != rune('#') {
							goto l50
						}
						position++
					case '@':
						if buffer[position] != rune('@') {
							goto l50
						}
						position++
					case '?':
						if buffer[position] != rune('?') {
							goto l50
						}
						position++
					case '*':
						if buffer[position] != rune('*') {
							goto l50
						}
						position++
					case '/':
						if buffer[position] != rune('/') {
							goto l50
						}
						position++
					case '.':
						if buffer[position] != rune('.') {
							goto l50
						}
						position++
					case '_':
						if buffer[position] != rune('_') {
							goto l50
						}
						position++
					case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
						if c := buffer[position]; c < rune('0') || c > rune('9') {
							goto l50
						}
						position++
					case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
						if c := buffer[position]; c < rune('a') || c > rune('z') {
							goto l50
						}
						position++
					default:
						if c := buffer[position]; c < rune('A') || c > rune('Z') {
							goto l50
						}
						position++
					}
				}

			l52:
				{
					position53, tokenIndex53 := position, tokenIndex
					{
						switch buffer[position] {
						case '\\':
							if buffer[position] != rune('\\') {
								goto l53
							}
							position++
							if !matchDot() {
								goto l53
							}
						case '-':
							if buffer[position] != rune('-') {
								goto l53
							}
							position++
						case '!':
							if buffer[position] != rune('!') {
								goto l53
							}
							position++
						case '$':
							if buffer[position] != rune('$') {
								goto l53
							}
							position++
						case '#':
							if buffer[position] != rune('#') {
								goto l53
							}
							position++
						case '@':
							if buffer[position] != rune('@') {
								goto l53
							}
							position++
						case '?':
							if buffer[position] != rune('?') {
								goto l53
							}
							position++
						case '*':
							if buffer[position] != rune('*') {
								goto l53
							}
							position++
						case '/':
							if buffer[position] != rune('/') {
								goto l53
							}
							position++
						case '.':
							if buffer[position] != rune('.') {
								goto l53
							}
							position++
						case '_':
							if buffer[position] != rune('_') {
								goto l53
							}
							position++
						case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
							if c := buffer[position]; c < rune('0') || c > rune('9') {
								goto l53
							}
							position++
						case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
							if c := buffer[position]; c < rune('a') || c > rune('z') {
								goto l53
							}
							position++
						default:
							if c := buffer[position]; c < rune('A') || c > rune('Z') {
								goto l53
							}
							position++
						}
					}

					goto l52
				l53:
					position, tokenIndex = position53, tokenIndex53
				}
				add(ruleSelectorValue, position51)
			}
			return true
		l50:
			position, tokenIndex = position50, tokenIndex50
			return false
		},
		/* 10 Symbol <- <(<(((&('?') '?') | (&('*') '*') | (&('_') '_') | (&('a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g' | 'h' | 'i' | 'j' | 'k' | 'l' | 'm' | 'n' | 'o' | 'p' | 'q' | 'r' | 's' | 't' | 'u' | 'v' | 'w' | 'x' | 'y' | 'z') [a-z]) | (&('A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | 'H' | 'I' | 'J' | 'K' | 'L' | 'M' | 'N' | 'O' | 'P' | 'Q' | 'R' | 'S' | 'T' | 'U' | 'V' | 'W' | 'X' | 'Y' | 'Z') [A-Z])) ((&('-') '-') | (&('?') '?') | (&('*') '*') | (&('/') '/') | (&('.') '.') | (&('_') '_') | (&('0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9') [0-9]) | (&('a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g' | 'h' | 'i' | 'j' | 'k' | 'l' | 'm' | 'n' | 'o' | 'p' | 'q' | 'r' | 's' | 't' | 'u' | 'v' | 'w' | 'x' | 'y' | 'z') [a-z]) | (&('A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | 'H' | 'I' | 'J' | 'K' | 'L' | 'M' | 'N' | 'O' | 'P' | 'Q' | 'R' | 'S' | 'T' | 'U' | 'V' | 'W' | 'X' | 'Y' | 'Z') [A-Z]))*)> Action2)> */
		func() bool {
			position56, tokenIndex56 := position, tokenIndex
			{
				position57 := position
				{
					position58 := position
					{
						switch buffer[position] {
						case '?':
							if buffer[position] != rune('?') {
								goto l56
							}
							position++
						case '*':
							if buffer[position] != rune('*') {
								goto l56
							}
							position++
						case '_':
							if buffer[position] != rune('_') {
								goto l56
							}
							position++
						case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
							if c := buffer[position]; c < rune('a') || c > rune('z') {
								goto l56
							}
							position++
						default:
							if c := buffer[position]; c < rune('A') || c > rune('Z') {
								goto l56
							}
							position++
						}
					}

				l60:
					{
						position61, tokenIndex61 := position, tokenIndex
						{
							switch buffer[position] {
							case '-':
								if buffer[position] != rune('-') {
									goto l61
								}
								position++
							case '?':
								if buffer[position] != rune('?') {
									goto l61
								}
								position++
							case '*':
								if buffer[position] != rune('*') {
									goto l61
								}
								position++
							case '/':
								if buffer[position] != rune('/') {
									goto l61
								}
								position++
							case '.':
								if buffer[position] != rune('.') {
									goto l61
								}
								position++
							case '_':
								if buffer[position] != rune('_') {
									goto l61
								}
								position++
							case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
								if c := buffer[position]; c < rune('0') || c > rune('9') {
									goto l61
								}
								position++
							case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
								if c := buffer[position]; c < rune('a') || c > rune('z') {
									goto l61
								}
								position++
							default:
								if c := buffer[position]; c < rune('A') || c > rune('Z') {
									goto l61
								}
								position++
							}
						}

						goto l60
					l61:
						position, tokenIndex = position61, tokenIndex61
					}
					begin := position58
					end := position
					text = string(buffer[begin:end])
				}
				if !_rules[ruleAction2]() {
					goto l56
				}
				add(ruleSymbol, position57)
			}
			return true
		l56:
			position, tokenIndex = position56, tokenIndex56
			return false
		},
		/* 11 Relation <- <(Transitive / Implementers / Inheritors / ((&('~') Writes) | (&('=') Definition) | (&('>') Outgoing) | (&('<') Incoming) | (&(':') Methods)))> */
		func() bool {
			position63, tokenIndex63 := position, tokenIndex
			{
				position64 := position
				{
					position65, tokenIndex65 := position, tokenIndex
					if !_rules[ruleTransitive]() {
						goto l66
					}
					goto l65
				l66:
					position, tokenIndex = position65, tokenIndex65
					if !_rules[ruleImplementers]() {
						goto l67
					}
					goto l65
				l67:
					position, tokenIndex = position65, tokenIndex65
					if !_rules[ruleInheritors]() {
						goto l68
					}
					goto l65
				l68:
					position, tokenIndex = position65, tokenIndex65
					{
						switch buffer[position] {
						case '~':
							if !_rules[ruleWrites]() {
								goto l63
							}
						case '=':
							if !_rules[ruleDefinition]() {
								goto l63
							}
						case '>':
							if !_rules[ruleOutgoing]() {
								goto l63
							}
						case '<':
							if !_rules[ruleIncoming]() {
								goto l63
							}
						default:
							if !_rules[ruleMethods]() {
								goto l63
							}
						}
					}

				}
			l65:
				add(ruleRelation, position64)
			}
			return true
		l63:
			position, tokenIndex = position63, tokenIndex63
			return false
		},
		/* 12 Transitive <- <('<' '<' <[0-9]*> Action3)> */
		func() bool {
			position70, tokenIndex70 := position, tokenIndex
			{
				position71 := position
				if buffer[position] != rune('<') {
					goto l70
				}
				position++
				if buffer[position] != rune('<') {
					goto l70
				}
				position++
				{
					position72 := position
				l73:
					{
						position74, tokenIndex74 := position, tokenIndex
						if c := buffer[position]; c < rune('0') || c > rune('9') {
							goto l74
						}
						position++
						goto l73
					l74:
						position, tokenIndex = position74, tokenIndex74
					}
					begin := position72
					end := position
					text = string(buffer[begin:end])
				}
				if !_rules[ruleAction3]() {
					goto l70
				}
				add(ruleTransitive, position71)
			}
			return true
		l70:
			position, tokenIndex = position70, tokenIndex70
			return false
		},
		/* 13 Implementers <- <(':' 'i' 'm' 'p' 'l' Action4)> */
		func() bool {
			position75, tokenIndex75 := position, tokenIndex
			{
				position76 := position
				if buffer[position] != rune(':') {
					goto l75
				}
				position++
				if buffer[position] != rune('i') {
					goto l75
				}
				position++
				if buffer[position] != rune('m') {
					goto l75
				}
				position++
				if buffer[position] != rune('p') {
					goto l75
				}
				position++
				if buffer[position] != rune('l') {
					goto l75
				}
				position++
				if !_rules[ruleAction4]() {
					goto l75
				}
				add(ruleImplementers, position76)
			}
			return true
		l75:
			position, tokenIndex = position75, tokenIndex75
			return false
		},
		/* 14 Inheritors <- <(':' 'i' 'n' 'h' 'e' 'r' 'i' 't' 's' Action5)> */
		func() bool {
			position77, tokenIndex77 := position, tokenIndex
			{
				position78 := position
				if buffer[position] != rune(':') {
					goto l77
				}
				position++
				if buffer[position] != rune('i') {
					goto l77
				}
				position++
				if buffer[position] != rune('n') {
					goto l77
				}
				position++
				if buffer[position] != rune('h') {
					goto l77
				}
				position++
				if buffer[position] != rune('e') {
					goto l77
				}
				position++
				if buffer[position] != rune('r') {
					goto l77
				}
				position++
				if buffer[position] != rune('i') {
					goto l77
				}
				position++
				if buffer[position] != rune('t') {
					goto l77
				}
				position++
				if buffer[position] != rune('s') {
					goto l77
				}
				position++
				if !_rules[ruleAction5]() {
					goto l77
				}
				add(ruleInheritors, position78)
			}
			return true
		l77:
			position, tokenIndex = position77, tokenIndex77
			return false
		},
		/* 15 Methods <- <(':' 'm' 'e' 't' 'h' 'o' 'd' 's' Action6)> */
		func() bool {
			position79, tokenIndex79 := position, tokenIndex
			{
				position80 := position
				if buffer[position] != rune(':') {
					goto l79
				}
				position++
				if buffer[position] != rune('m') {
					goto l79
				}
				position++
				if buffer[position] != rune('e') {
					goto l79
				}
				position++
				if buffer[position] != rune('t') {
					goto l79
				}
				position++
				if buffer[position] != rune('h') {
					goto l79
				}
				position++
				if buffer[position] != rune('o') {
					goto l79
				}
				position++
				if buffer[position] != rune('d') {
					goto l79
				}
				position++
				if buffer[position] != rune('s') {
					goto l79
				}
				position++
				if !_rules[ruleAction6]() {
					goto l79
				}
				add(ruleMethods, position80)
			}
			return true
		l79:
			position, tokenIndex = position79, tokenIndex79
			return false
		},
		/* 16 Incoming <- <('<' Action7)> */
		func() bool {
			position81, tokenIndex81 := position, tokenIndex
			{
				position82 := position
				if buffer[position] != rune('<') {
					goto l81
				}
				position++
				if !_rules[ruleAction7]() {
					goto l81
				}
				add(ruleIncoming, position82)
			}
			return true
		l81:
			position, tokenIndex = position81, tokenIndex81
			return false
		},
		/* 17 Outgoing <- <('>' Action8)> */
		func() bool {
			position83, tokenIndex83 := position, tokenIndex
			{
				position84 := position
				if buffer[position] != rune('>') {
					goto l83
				}
				position++
				if !_rules[ruleAction8]() {
					goto l83
				}
				add(ruleOutgoing, position84)
			}
			return true
		l83:
			position, tokenIndex = position83, tokenIndex83
			return false
		},
		/* 18 Definition <- <('=' Action9)> */
		func() bool {
			position85, tokenIndex85 := position, tokenIndex
			{
				position86 := position
				if buffer[position] != rune('=') {
					goto l85
				}
				position++
				if !_rules[ruleAction9]() {
					goto l85
				}
				add(ruleDefinition, position86)
			}
			return true
		l85:
			position, tokenIndex = position85, tokenIndex85
			return false
		},
		/* 19 Writes <- <('~' 'w' Action10)> */
		func() bool {
			position87, tokenIndex87 := position, tokenIndex
			{
				position88 := position
				if buffer[position] != rune('~') {
					goto l87
				}
				position++
				if buffer[position] != rune('w') {
					goto l87
				}
				position++
				if !_rules[ruleAction10]() {
					goto l87
				}
				add(ruleWrites, position88)
			}
			return true
		l87:
			position, tokenIndex = position87, tokenIndex87
			return false
		},
		/* 20 Filter <- <(RoleFilter / ValueFilter)> */
		func() bool {
			position89, tokenIndex89 := position, tokenIndex
			{
				position90 := position
				{
					position91, tokenIndex91 := position, tokenIndex
					if !_rules[ruleRoleFilter]() {
						goto l92
					}
					goto l91
				l92:
					position, tokenIndex = position91, tokenIndex91
					if !_rules[ruleValueFilter]() {
						goto l89
					}
				}
			l91:
				add(ruleFilter, position90)
			}
			return true
		l89:
			position, tokenIndex = position89, tokenIndex89
			return false
		},
		/* 21 RoleFilter <- <(<('~' 'w')> Action11)> */
		func() bool {
			position93, tokenIndex93 := position, tokenIndex
			{
				position94 := position
				{
					position95 := position
					if buffer[position] != rune('~') {
						goto l93
					}
					position++
					if buffer[position] != rune('w') {
						goto l93
					}
					position++
					begin := position95
					end := position
					text = string(buffer[begin:end])
				}
				if !_rules[ruleAction11]() {
					goto l93
				}
				add(ruleRoleFilter, position94)
			}
			return true
		l93:
			position, tokenIndex = position93, tokenIndex93
			return false
		},
		/* 22 ValueFilter <- <(<(('-' 'f') / ('+' 'p' 'k' 'g') / ('-' 'p' 'k' 'g'))> Action12 Spacing Value)> */
		func() bool {
			position96, tokenIndex96 := position, tokenIndex
			{
				position97 := position
				{
					position98 := position
					{
						position99, tokenIndex99 := position, tokenIndex
						if buffer[position] != rune('-') {
							goto l100
						}
						position++
						if buffer[position] != rune('f') {
							goto l100
						}
						position++
						goto l99
					l100:
						position, tokenIndex = position99, tokenIndex99
						if buffer[position] != rune('+') {
							goto l101
						}
						position++
						if buffer[position] != rune('p') {
							goto l101
						}
						position++
						if buffer[position] != rune('k') {
							goto l101
						}
						position++
						if buffer[position] != rune('g') {
							goto l101
						}
						position++
						goto l99
					l101:
						position, tokenIndex = position99, tokenIndex99
						if buffer[position] != rune('-') {
							goto l96
						}
						position++
						if buffer[position] != rune('p') {
							goto l96
						}
						position++
						if buffer[position] != rune('k') {
							goto l96
						}
						position++
						if buffer[position] != rune('g') {
							goto l96
						}
						position++
					}
				l99:
					begin := position98
					end := position
					text = string(buffer[begin:end])
				}
				if !_rules[ruleAction12]() {
					goto l96
				}
				if !_rules[ruleSpacing]() {
					goto l96
				}
				if !_rules[ruleValue]() {
					goto l96
				}
				add(ruleValueFilter, position97)
			}
			return true
		l96:
			position, tokenIndex = position96, tokenIndex96
			return false
		},
		/* 23 Value <- <(<((&('-') '-') | (&('*') '*') | (&('/') '/') | (&('.') '.') | (&('_') '_') | (&('0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9') [0-9]) | (&('a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g' | 'h' | 'i' | 'j' | 'k' | 'l' | 'm' | 'n' | 'o' | 'p' | 'q' | 'r' | 's' | 't' | 'u' | 'v' | 'w' | 'x' | 'y' | 'z') [a-z]) | (&('A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | 'H' | 'I' | 'J' | 'K' | 'L' | 'M' | 'N' | 'O' | 'P' | 'Q' | 'R' | 'S' | 'T' | 'U' | 'V' | 'W' | 'X' | 'Y' | 'Z') [A-Z]))+> Action13)> */
		func() bool {
			position102, tokenIndex102 := position, tokenIndex
			{
				position103 := position
				{
					position104 := position
					{
						switch buffer[position] {
						case '-':
							if buffer[position] != rune('-') {
								goto l102
							}
							position++
						case '*':
							if buffer[position] != rune('*') {
								goto l102
							}
							position++
						case '/':
							if buffer[position] != rune('/') {
								goto l102
							}
							position++
						case '.':
							if buffer[position] != rune('.') {
								goto l102
							}
							position++
						case '_':
							if buffer[position] != rune('_') {
								goto l102
							}
							position++
						case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
							if c := buffer[position]; c < rune('0') || c > rune('9') {
								goto l102
							}
							position++
						case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
							if c := buffer[position]; c < rune('a') || c > rune('z') {
								goto l102
							}
							position++
						default:
							if c := buffer[position]; c < rune('A') || c > rune('Z') {
								goto l102
							}
							position++
						}
					}

				l105:
					{
						position106, tokenIndex106 := position, tokenIndex
						{
							switch buffer[position] {
							case '-':
								if buffer[position] != rune('-') {
									goto l106
								}
								position++
							case '*':
								if buffer[position] != rune('*') {
									goto l106
								}
								position++
							case '/':
								if buffer[position] != rune('/') {
									goto l106
								}
								position++
							case '.':
								if buffer[position] != rune('.') {
									goto l106
								}
								position++
							case '_':
								if buffer[position] != rune('_') {
									goto l106
								}
								position++
							case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
								if c := buffer[position]; c < rune('0') || c > rune('9') {
									goto l106
								}
								position++
							case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
								if c := buffer[position]; c < rune('a') || c > rune('z') {
									goto l106
								}
								position++
							default:
								if c := buffer[position]; c < rune('A') || c > rune('Z') {
									goto l106
								}
								position++
							}
						}

						goto l105
					l106:
						position, tokenIndex = position106, tokenIndex106
					}
					begin := position104
					end := position
					text = string(buffer[begin:end])
				}
				if !_rules[ruleAction13]() {
					goto l102
				}
				add(ruleValue, position103)
			}
			return true
		l102:
			position, tokenIndex = position102, tokenIndex102
			return false
		},
		/* 24 PathStep <- <(PathOperator _ Primary)> */
		func() bool {
			position109, tokenIndex109 := position, tokenIndex
			{
				position110 := position
				if !_rules[rulePathOperator]() {
					goto l109
				}
				if !_rules[rule_]() {
					goto l109
				}
				if !_rules[rulePrimary]() {
					goto l109
				}
				add(rulePathStep, position110)
			}
			return true
		l109:
			position, tokenIndex = position109, tokenIndex109
			return false
		},
		/* 25 PathOperator <- <('>' '>' <[0-9]*> Action14)> */
		func() bool {
			position111, tokenIndex111 := position, tokenIndex
			{
				position112 := position
				if buffer[position] != rune('>') {
					goto l111
				}
				position++
				if buffer[position] != rune('>') {
					goto l111
				}
				position++
				{
					position113 := position
				l114:
					{
						position115, tokenIndex115 := position, tokenIndex
						if c := buffer[position]; c < rune('0') || c > rune('9') {
							goto l115
						}
						position++
						goto l114
					l115:
						position, tokenIndex = position115, tokenIndex115
					}
					begin := position113
					end := position
					text = string(buffer[begin:end])
				}
				if !_rules[ruleAction14]() {
					goto l111
				}
				add(rulePathOperator, position112)
			}
			return true
		l111:
			position, tokenIndex = position111, tokenIndex111
			return false
		},
		/* 26 UnionOperator <- <('|' Action15)> */
		func() bool {
			position116, tokenIndex116 := position, tokenIndex
			{
				position117 := position
				if buffer[position] != rune('|') {
					goto l116
				}
				position++
				if !_rules[ruleAction15]() {
					goto l116
				}
				add(ruleUnionOperator, position117)
			}
			return true
		l116:
			position, tokenIndex = position116, tokenIndex116
			return false
		},
		/* 27 IntersectionOperator <- <('&' Action16)> */
		func() bool {
			position118, tokenIndex118 := position, tokenIndex
			{
				position119 := position
				if buffer[position] != rune('&') {
					goto l118
				}
				position++
				if !_rules[ruleAction16]() {
					goto l118
				}
				add(ruleIntersectionOperator, position119)
			}
			return true
		l118:
			position, tokenIndex = position118, tokenIndex118
			return false
		},
		/* 28 Open <- <('(' Action17)> */
		func() bool {
			position120, tokenIndex120 := position, tokenIndex
			{
				position121 := position
				if buffer[position] != rune('(') {
					goto l120
				}
				position++
				if !_rules[ruleAction17]() {
					goto l120
				}
				add(ruleOpen, position121)
			}
			return true
		l120:
			position, tokenIndex = position120, tokenIndex120
			return false
		},
		/* 29 Close <- <(')' Action18)> */
		func() bool {
			position122, tokenIndex122 := position, tokenIndex
			{
				position123 := position
				if buffer[position] != rune(')') {
					goto l122
				}
				position++
				if !_rules[ruleAction18]() {
					goto l122
				}
				add(ruleClose, position123)
			}
			return true
		l122:
			position, tokenIndex = position122, tokenIndex122
			return false
		},
		/* 30 Spacing <- <((&('\n') '\n') | (&('\r') '\r') | (&('\t') '\t') | (&(' ') ' '))+> */
		func() bool {
			position124, tokenIndex124 := position, tokenIndex
			{
				position125 := position
				{
					switch buffer[position] {
					case '\n':
						if buffer[position] != rune('\n') {
							goto l124
						}
						position++
					case '\r':
						if buffer[position] != rune('\r') {
							goto l124
						}
						position++
					case '\t':
						if buffer[position] != rune('\t') {
							goto l124
						}
						position++
					default:
						if buffer[position] != rune(' ') {
							goto l124
						}
						position++
					}
				}

			l126:
				{
					position127, tokenIndex127 := position, tokenIndex
					{
						switch buffer[position] {
						case '\n':
							if buffer[position] != rune('\n') {
								goto l127
							}
							position++
						case '\r':
							if buffer[position] != rune('\r') {
								goto l127
							}
							position++
						case '\t':
							if buffer[position] != rune('\t') {
								goto l127
							}
							position++
						default:
							if buffer[position] != rune(' ') {
								goto l127
							}
							position++
						}
					}

					goto l126
				l127:
					position, tokenIndex = position127, tokenIndex127
				}
				add(ruleSpacing, position125)
			}
			return true
		l124:
			position, tokenIndex = position124, tokenIndex124
			return false
		},
		/* 31 _ <- <((&('\n') '\n') | (&('\r') '\r') | (&('\t') '\t') | (&(' ') ' '))*> */
		func() bool {
			{
				position131 := position
			l132:
				{
					position133, tokenIndex133 := position, tokenIndex
					{
						switch buffer[position] {
						case '\n':
							if buffer[position] != rune('\n') {
								goto l133
							}
							position++
						case '\r':
							if buffer[position] != rune('\r') {
								goto l133
							}
							position++
						case '\t':
							if buffer[position] != rune('\t') {
								goto l133
							}
							position++
						default:
							if buffer[position] != rune(' ') {
								goto l133
							}
							position++
						}
					}

					goto l132
				l133:
					position, tokenIndex = position133, tokenIndex133
				}
				add(rule_, position131)
			}
			return true
		},
		nil,
		/* 34 Action0 <- <{ p.addToken("selector", text) }> */
		func() bool {
			{
				p.addToken("selector", text)
			}
			return true
		},
		/* 35 Action1 <- <{ p.addToken("modifier", text) }> */
		func() bool {
			{
				p.addToken("modifier", text)
			}
			return true
		},
		/* 36 Action2 <- <{ p.addToken("symbol", text) }> */
		func() bool {
			{
				p.addToken("symbol", text)
			}
			return true
		},
		/* 37 Action3 <- <{ p.addToken("relation", "<<" + text) }> */
		func() bool {
			{
				p.addToken("relation", "<<"+text)
			}
			return true
		},
		/* 38 Action4 <- <{ p.addToken("relation", ":impl") }> */
		func() bool {
			{
				p.addToken("relation", ":impl")
			}
			return true
		},
		/* 39 Action5 <- <{ p.addToken("relation", ":inherits") }> */
		func() bool {
			{
				p.addToken("relation", ":inherits")
			}
			return true
		},
		/* 40 Action6 <- <{ p.addToken("relation", ":methods") }> */
		func() bool {
			{
				p.addToken("relation", ":methods")
			}
			return true
		},
		/* 41 Action7 <- <{ p.addToken("relation", "<") }> */
		func() bool {
			{
				p.addToken("relation", "<")
			}
			return true
		},
		/* 42 Action8 <- <{ p.addToken("relation", ">") }> */
		func() bool {
			{
				p.addToken("relation", ">")
			}
			return true
		},
		/* 43 Action9 <- <{ p.addToken("relation", "=") }> */
		func() bool {
			{
				p.addToken("relation", "=")
			}
			return true
		},
		/* 44 Action10 <- <{ p.addToken("relation", "~w") }> */
		func() bool {
			{
				p.addToken("relation", "~w")
			}
			return true
		},
		/* 45 Action11 <- <{ p.addToken("filter", text) }> */
		func() bool {
			{
				p.addToken("filter", text)
			}
			return true
		},
		/* 46 Action12 <- <{ p.addToken("filter", text) }> */
		func() bool {
			{
				p.addToken("filter", text)
			}
			return true
		},
		/* 47 Action13 <- <{ p.addToken("value", text) }> */
		func() bool {
			{
				p.addToken("value", text)
			}
			return true
		},
		/* 48 Action14 <- <{ p.addToken("path", ">>" + text) }> */
		func() bool {
			{
				p.addToken("path", ">>"+text)
			}
			return true
		},
		/* 49 Action15 <- <{ p.addToken("or", "|") }> */
		func() bool {
			{
				p.addToken("or", "|")
			}
			return true
		},
		/* 50 Action16 <- <{ p.addToken("and", "&") }> */
		func() bool {
			{
				p.addToken("and", "&")
			}
			return true
		},
		/* 51 Action17 <- <{ p.addToken("open", "(") }> */
		func() bool {
			{
				p.addToken("open", "(")
			}
			return true
		},
		/* 52 Action18 <- <{ p.addToken("close", ")") }> */
		func() bool {
			{
				p.addToken("close", ")")
			}
			return true
		},
	}
	p.rules = _rules
	return nil
}
