# Code generated by cmd/genschema from uir.StatementMarshaler; DO NOT EDIT.
# Run `make schema` after registering a statement kind.
"""The statement kinds Go registers, which a refined statement type resolves to."""

# Every kind uir.StatementMarshaler registers.
REGISTERED_KINDS = frozenset([
    "assignment",
    "assignment:binary",
    "assignment:cast",
    "assignment:destructure",
    "assignment:expression",
    "assignment:literal",
    "assignment:object",
    "assignment:template",
    "assignment:tuple",
    "assignment:unary",
    "assignment:variable",
    "call",
    "call:api",
    "call:read:record",
    "call:write:record",
    "control:block",
    "control:break",
    "control:condition",
    "control:continue",
    "control:if",
    "control:loop:for",
    "control:loop:foreach",
    "control:loop:while",
    "control:return",
    "control:switch",
    "control:throw",
    "control:try",
    "decl:const",
    "decl:func",
    "decl:type",
    "decl:var",
    "doc",
    "raw",
    "ref:var",
    "test",
])

# The refinements a kind accepts from outside its own ':'-hierarchy.
CROSS_HIERARCHY = {
    "control:block": frozenset(["doc"]),
}
