# generated by datamodel-codegen:
#   filename:  uir.schema.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Literal, TypeAlias, Union

ASTErrorType: TypeAlias = Literal['syntax', 'validation', 'compilation', 'runtime', 'configuration', 'network', 'auth', 'authz', 'timeout']


AssignmentOp: TypeAlias = Literal['=', '+=', '-=', '*=', '/=', '%=', '&=', '|=', '**=', '??=', '&&=', '||=', 'append']


BinaryOp: TypeAlias = Literal['&&', '||', '==', '!=', '<', '<=', '>', '>=', '+', '-', '*', '/', '%', 'like', 'ilike', 'regex', 'startsWith', 'endsWith', 'contains', '??', '?.', 'in', 'instanceof', '**', '&', '|', '^', '<<', '>>', '>>>', '===', '!==']


CommentType: TypeAlias = Literal['single_line', 'multi_line', 'documentation']


DocType: TypeAlias = Literal['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'comment', 'paragraph', 'document', 'blockquote', 'snippet', 'list', 'list_item', 'code_block']


EndpointPointMethod: TypeAlias = Literal['GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'OPTIONS', 'HEAD']


EndpointType: TypeAlias = Literal['soap', 'jms', 'kafka', 'tcp', 'http', 'grpc', 'graphql']


@dataclass
class ExportSpec:
    alias: str | None = None
    kind: str | None = None
    module: str | None = None
    name: str | None = None


ExpressionType: TypeAlias = Literal['sql', 'xpath', 'jsonpath', 'regex', 'jq', 'yq', 'jmespath', 'cel', 'SpEL', 'ognl']


@dataclass
class HierarchyEdge:
    edgeKind: str | None = None
    name: str | None = None
    order: int | None = None
    targetId: str | None = None


@dataclass
class ImportNamedSpec:
    alias: str | None = None
    name: str | None = None


@dataclass
class ImportSpec:
    defaultName: str | None = None
    module: str | None = None
    named: list[ImportNamedSpec] | None = None
    namespaceName: str | None = None
    typeOnly: bool | None = None


NodeType: TypeAlias = Literal['package', 'class', 'method', 'module', 'record', 'endpoint', 'function', 'record_field', 'table', 'column', 'index', 'foreign_key', 'dependency', 'interface', 'constructor', 'function_variable', 'package_variable', 'import', 'annotation', 'comment', 'ref', '', 'statement']


@dataclass
class RawFile:
    content: str
    path: str


RecordFieldType: TypeAlias = Literal['string', 'number', 'boolean', 'array', 'object', 'enum', 'date', 'float', 'int', 'ip', 'cidr', 'url', 'email', 'uuid', 'json', 'jsonb', 'yaml', 'xml', 'csv', 'phone', 'text', 'secret', 'map']


RecordReferenceType: TypeAlias = Literal['foreignKey', 'softKey']


RecordType: TypeAlias = Literal['input', 'output', 'sql:table', 'sql:view', 'sql:index', 'sql:stored_proc', 'sql:function', 'sql:trigger', 'cache', 'file:yaml', 'file:json', 'file:xml', 'file:csv', 'other']


@dataclass
class SourceCode:
    column: int | None = None
    content: str | None = None
    end_line: int | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    start_line: int | None = None


StatementType: TypeAlias = Literal['call', 'decl', 'call:package', 'call:read', 'call:write', 'call:read:record', 'call:write:record', 'decl:import', 'decl:var', 'decl:const', 'decl:func', 'decl:type', 'decl:export', 'ref', 'ref:var', 'ref:package', 'ref:endpoint', 'ref:record', 'call:read:kafka', 'call:write:kafka', 'call:read:jms', 'call:write:jms', 'call:read:file', 'call:write:file', 'call:api', 'call:api:http', 'call:api:soap', 'call:api:grpc', 'call:api:graphql', 'call:api:tcp', 'other', 'control:if', 'control:loop', 'control:loop:for', 'control:loop:foreach', 'control:loop:while', 'control:switch', 'control:throw', 'control:try', 'control:block', 'control:condition', 'control:return', 'control:break', 'control:continue', 'assignment:expression', 'assignment', 'assignment:literal', 'assignment:tuple', 'assignment:object', 'assignment:variable', 'assignment:array', 'assignment:binary', 'assignment:unary', 'assignment:cast', 'doc', 'test', 'assignment:destructure', 'raw', 'assignment:template', 'foreign_key', 'dispatch_call']


@dataclass
class TypeReference:
    fieldType: RecordFieldType | None = None
    functionParams: list[TypeReference] | None = None
    functionReturns: TypeReference | None = None
    intersection: list[TypeReference] | None = None
    isArray: bool | None = None
    literalValue: str | None = None
    name: str | None = None
    optional: bool | None = None
    package: str | None = None
    rawType: str | None = None
    tupleElements: list[TypeReference] | None = None
    typeArgs: list[TypeReference] | None = None
    union: list[TypeReference] | None = None


@dataclass
class UIRSymbolRef:
    method: str | None = None
    module: str | None = None
    name: str | None = None
    package: str | None = None
    symbolKind: str | None = None
    type: str | None = None


UnaryOp: TypeAlias = Literal['!', '-', '+', '++', '--', '*', '&', 'typeof', 'void', 'delete', 'await', 'yield', '...', '~', 'keyof', 'readonly']


UnitType: TypeAlias = Literal['metric', 'imperial', 'si', 'percentage', 'bytes', 'seconds', 'milliseconds', 'nanoseconds', 'epoch', 'currency']


@dataclass
class ValidationValue:
    arrayValue: list[ValidationValue] | None = None
    boolValue: bool | None = None
    code: str | None = None
    numberValue: float | None = None
    objectValue: dict[str, ValidationValue] | None = None
    stringValue: str | None = None


Visibility: TypeAlias = Literal['public', 'private', 'protected', 'internal', 'package', '']


@dataclass
class Comment:
    type: CommentType | Literal['']
    column: int | None = None
    context: str | None = None
    end_line: int | None = None
    last_modified: str | None = None
    path: str | None = None
    start_line: int | None = None
    text: str | None = None


@dataclass
class Expression:
    column: int | None = None
    content: str | None = None
    end_line: int | None = None
    expression: str | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    start_line: int | None = None
    type: ExpressionType | None = None


@dataclass
class GeneratorHint:
    framework: str | None = None
    language: str | None = None
    properties: dict[str, ValidationValue] | None = None


@dataclass
class HierarchyAttachment:
    placementName: str | None = None
    role: str | None = None
    symbolRef: UIRSymbolRef | None = None


@dataclass
class NodeNodeRef:
    node_kind: Literal['ref']
    field: str | None = None
    id: str | None = None
    method: str | None = None
    module: str | None = None
    node_type: NodeType | None = None
    package: str | None = None
    signature: str | None = None
    type: str | None = None


@dataclass
class NodeRef:
    field: str | None = None
    id: str | None = None
    method: str | None = None
    module: str | None = None
    node_kind: Literal['ref'] | None = None
    node_type: NodeType | None = None
    package: str | None = None
    signature: str | None = None
    type: str | None = None


@dataclass
class RecordReference:
    name: str
    mapping: str | None = None
    recordReferenceType: RecordReferenceType | None = None


@dataclass
class TypeParam:
    name: str
    constraint: TypeReference | None = None
    default: TypeReference | None = None


@dataclass
class Unit:
    type: UnitType | None = None
    value: str | None = None


@dataclass
class ValidationRuleOptions:
    always: bool | None = None
    context: dict[str, ValidationValue] | None = None
    each: bool | None = None
    groups: list[str] | None = None
    message: str | None = None


@dataclass
class TypedValue:
    bool: bool | None = None
    date: str | None = None
    float: float | None = None
    int: int | None = None
    string: str | None = None
    unit: Unit | None = None


@dataclass
class ValidationRule:
    name: str
    args: list[ValidationValue] | None = None
    options: ValidationRuleOptions | None = None
    provider: str | None = None


@dataclass
class ASTError:
    name: str
    code: TypedValue | None = None
    description: str | None = None
    errorType: ASTErrorType | None = None
    id: str | None = None
    idSourceCode: SourceCode | None = None
    sourceCode: SourceCode | None = None


@dataclass
class Annotation:
    field: str | None = None
    id: str | None = None
    method: str | None = None
    module: str | None = None
    node_type: NodeType | None = None
    package: str | None = None
    signature: str | None = None
    type: str | None = None
    value: TypedValue | None = None
    values: dict[str, TypedValue] | None = None


@dataclass
class BreakStmt:
    annotations: list[Annotation] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['control:break'] | str | None = None
    statement_type: Literal['control:break'] | None = None


@dataclass
class ContinueStmt:
    annotations: list[Annotation] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['control:continue'] | str | None = None
    statement_type: Literal['control:continue'] | None = None


@dataclass
class DocStmt:
    annotations: list[Annotation] | None = None
    children: list[DocStmt] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    doc_type: DocType | None = None
    end_line: int | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['doc'] | str | None = None
    statement_type: Literal['doc'] | None = None
    style: str | None = None
    text: str | None = None


@dataclass
class HierarchyNode:
    attachments: list[HierarchyAttachment] | None = None
    children: list[HierarchyEdge] | None = None
    displayName: str | None = None
    exports: list[ExportSpec] | None = None
    id: str | None = None
    imports: list[ImportSpec] | None = None
    kind: str | None = None
    name: str | None = None
    properties: dict[str, str] | None = None
    sourceCode: SourceCode | None = None
    values: dict[str, TypedValue] | None = None


@dataclass
class LiteralStmt:
    annotations: list[Annotation] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    fieldType: RecordFieldType | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['assignment:literal'] | str | None = None
    statement_type: Literal['assignment:literal'] | None = None
    value: str | None = None


@dataclass
class NodeRecordColumn:
    node_kind: Literal['column']
    annotations: list[Annotation] | None = None
    autoIncrement: bool | None = None
    comments: list[Comment] | None = None
    defaultValue: TypedValue | None = None
    enum: list[str] | None = None
    field: str | None = None
    fieldType: RecordFieldType | None = None
    id: str | None = None
    label: str | None = None
    maxLength: int | None = None
    method: str | None = None
    module: str | None = None
    node_type: NodeType | None = None
    nullable: bool | None = None
    ordinal: int | None = None
    package: str | None = None
    precision: int | None = None
    primaryKey: bool | None = None
    properties: dict[str, Any] | None = None
    scale: int | None = None
    signature: str | None = None
    sourceCode: SourceCode | None = None
    sqlType: str | None = None
    type: str | None = None
    unique: bool | None = None


@dataclass
class NodeRecordForeignKey:
    node_kind: Literal['foreign_key']
    annotations: list[Annotation] | None = None
    columns: list[str] | None = None
    comments: list[Comment] | None = None
    field: str | None = None
    id: str | None = None
    method: str | None = None
    module: str | None = None
    node_type: NodeType | None = None
    onDelete: str | None = None
    onUpdate: str | None = None
    package: str | None = None
    properties: dict[str, Any] | None = None
    referencedColumns: list[str] | None = None
    referencedSchema: str | None = None
    referencedTable: str | None = None
    signature: str | None = None
    sourceCode: SourceCode | None = None
    type: str | None = None


@dataclass
class NodeRecordIndex:
    node_kind: Literal['index']
    annotations: list[Annotation] | None = None
    clustered: bool | None = None
    columns: list[str] | None = None
    comments: list[Comment] | None = None
    condition: str | None = None
    field: str | None = None
    id: str | None = None
    included: list[str] | None = None
    indexType: str | None = None
    method: str | None = None
    module: str | None = None
    node_type: NodeType | None = None
    package: str | None = None
    primary: bool | None = None
    properties: dict[str, Any] | None = None
    signature: str | None = None
    sourceCode: SourceCode | None = None
    type: str | None = None
    unique: bool | None = None


@dataclass
class RawStmt:
    source: str
    annotations: list[Annotation] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    source_language: str | None = None
    start_line: int | None = None
    statement_refinement: Literal['raw'] | str | None = None
    statement_type: Literal['raw'] | None = None


@dataclass
class RecordColumn:
    annotations: list[Annotation] | None = None
    autoIncrement: bool | None = None
    comments: list[Comment] | None = None
    defaultValue: TypedValue | None = None
    enum: list[str] | None = None
    field: str | None = None
    fieldType: RecordFieldType | None = None
    id: str | None = None
    label: str | None = None
    maxLength: int | None = None
    method: str | None = None
    module: str | None = None
    node_kind: Literal['column'] | None = None
    node_type: NodeType | None = None
    nullable: bool | None = None
    ordinal: int | None = None
    package: str | None = None
    precision: int | None = None
    primaryKey: bool | None = None
    properties: dict[str, Any] | None = None
    scale: int | None = None
    signature: str | None = None
    sourceCode: SourceCode | None = None
    sqlType: str | None = None
    type: str | None = None
    unique: bool | None = None


@dataclass
class RecordForeignKey:
    annotations: list[Annotation] | None = None
    columns: list[str] | None = None
    comments: list[Comment] | None = None
    field: str | None = None
    id: str | None = None
    method: str | None = None
    module: str | None = None
    node_kind: Literal['foreign_key'] | None = None
    node_type: NodeType | None = None
    onDelete: str | None = None
    onUpdate: str | None = None
    package: str | None = None
    properties: dict[str, Any] | None = None
    referencedColumns: list[str] | None = None
    referencedSchema: str | None = None
    referencedTable: str | None = None
    signature: str | None = None
    sourceCode: SourceCode | None = None
    type: str | None = None


@dataclass
class RecordIndex:
    annotations: list[Annotation] | None = None
    clustered: bool | None = None
    columns: list[str] | None = None
    comments: list[Comment] | None = None
    condition: str | None = None
    field: str | None = None
    id: str | None = None
    included: list[str] | None = None
    indexType: str | None = None
    method: str | None = None
    module: str | None = None
    node_kind: Literal['index'] | None = None
    node_type: NodeType | None = None
    package: str | None = None
    primary: bool | None = None
    properties: dict[str, Any] | None = None
    signature: str | None = None
    sourceCode: SourceCode | None = None
    type: str | None = None
    unique: bool | None = None


@dataclass
class ScopedVariableRef:
    name: str
    defaultValue: TypedValue | None = None
    field: str | None = None
    id: str | None = None
    method: str | None = None
    module: str | None = None
    node_type: NodeType | None = None
    package: str | None = None
    signature: str | None = None
    statement_refinement: Literal['ref:var'] | str | None = None
    statement_type: Literal['ref:var'] | None = None
    type: str | None = None


@dataclass
class StatementBreakStmt:
    statement_type: Literal['control:break']
    annotations: list[Annotation] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['control:break'] | str | None = None


@dataclass
class StatementContinueStmt:
    statement_type: Literal['control:continue']
    annotations: list[Annotation] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['control:continue'] | str | None = None


@dataclass
class StatementDocStmt:
    statement_type: Literal['doc']
    annotations: list[Annotation] | None = None
    children: list[DocStmt] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    doc_type: DocType | None = None
    end_line: int | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['doc'] | str | None = None
    style: str | None = None
    text: str | None = None


@dataclass
class StatementLiteralStmt:
    statement_type: Literal['assignment:literal']
    annotations: list[Annotation] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    fieldType: RecordFieldType | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['assignment:literal'] | str | None = None
    value: str | None = None


@dataclass
class StatementRawStmt:
    source: str
    statement_type: Literal['raw']
    annotations: list[Annotation] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    source_language: str | None = None
    start_line: int | None = None
    statement_refinement: Literal['raw'] | str | None = None


@dataclass
class StatementScopedVariableRef:
    name: str
    statement_type: Literal['ref:var']
    defaultValue: TypedValue | None = None
    field: str | None = None
    id: str | None = None
    method: str | None = None
    module: str | None = None
    node_type: NodeType | None = None
    package: str | None = None
    signature: str | None = None
    statement_refinement: Literal['ref:var'] | str | None = None
    type: str | None = None


@dataclass
class StatementTypeDeclStmt:
    statement_type: Literal['decl:type']
    annotations: list[Annotation] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    language: str | None = None
    last_modified: str | None = None
    name: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['decl:type'] | str | None = None


@dataclass
class StatementVariableStmt:
    statement_type: Literal['assignment:variable']
    annotations: list[Annotation] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    language: str | None = None
    last_modified: str | None = None
    name: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['assignment:variable'] | str | None = None


@dataclass
class TypeDeclStmt:
    annotations: list[Annotation] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    language: str | None = None
    last_modified: str | None = None
    name: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['decl:type'] | str | None = None
    statement_type: Literal['decl:type'] | None = None


@dataclass
class VariableStmt:
    annotations: list[Annotation] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    language: str | None = None
    last_modified: str | None = None
    name: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['assignment:variable'] | str | None = None
    statement_type: Literal['assignment:variable'] | None = None


@dataclass
class HierarchyGraph:
    nodes: list[HierarchyNode] | None = None


UIR: TypeAlias = Union["UIRModel", list["Node"]]


@dataclass
class ASTEndpoint:
    annotations: list[Annotation] | None = None
    comments: list[Comment] | None = None
    endpointType: EndpointType | None = None
    errors: list[ASTError] | None = None
    examples: list[str] | None = None
    field: str | None = None
    httpMethod: EndpointPointMethod | None = None
    id: str | None = None
    input: ASTRecord | None = None
    method: str | None = None
    module: str | None = None
    node_kind: Literal['endpoint'] | None = None
    node_type: NodeType | None = None
    output: ASTRecord | None = None
    package: str | None = None
    properties: dict[str, Any] | None = None
    signature: str | None = None
    sourceCode: SourceCode | None = None
    type: str | None = None


@dataclass
class ASTRecord:
    annotations: list[Annotation] | None = None
    comments: list[Comment] | None = None
    description: str | None = None
    examples: list[str] | None = None
    extends: list[ASTRecord] | None = None
    field: str | None = None
    fields: list[RecordField] | None = None
    id: str | None = None
    method: str | None = None
    module: str | None = None
    node_kind: Literal['record'] | None = None
    node_type: NodeType | None = None
    package: str | None = None
    properties: dict[str, Any] | None = None
    recordType: RecordType | None = None
    references: list[RecordReference] | None = None
    signature: str | None = None
    sourceCode: SourceCode | None = None
    type: str | None = None
    validation: RecordValidation | None = None


@dataclass
class AssignmentStmt:
    annotations: list[Annotation] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    isDeclaration: bool | None = None
    language: str | None = None
    last_modified: str | None = None
    op: AssignmentOp | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['assignment'] | str | None = None
    statement_type: Literal['assignment'] | None = None
    target: ScopedVariableRef | None = None
    value: ExprStmt | None = None


@dataclass
class BinaryStmt:
    annotations: list[Annotation] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    language: str | None = None
    last_modified: str | None = None
    left: ExprStmt | None = None
    op: BinaryOp | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    right: ExprStmt | None = None
    start_line: int | None = None
    statement_refinement: Literal['assignment:binary'] | str | None = None
    statement_type: Literal['assignment:binary'] | None = None


@dataclass
class BlockStmt:
    annotations: list[Annotation] | None = None
    children: list[Statement] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['control:block'] | str | Literal['doc'] | None = None
    statement_type: Literal['control:block'] | None = None
    variables: list[RecordField] | None = None


@dataclass
class CastStmt:
    annotations: list[Annotation] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    expr: ExprStmt | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['assignment:cast'] | str | None = None
    statement_type: Literal['assignment:cast'] | None = None
    targetType: str | None = None


@dataclass
class ConditionStmt:
    annotations: list[Annotation] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    expr: ExprStmt | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['control:condition'] | str | None = None
    statement_type: Literal['control:condition'] | None = None


@dataclass
class ConditionalFieldValidation:
    condition: Expression
    validation: FieldValidation


@dataclass
class ConditionalRecordValidation:
    condition: Expression
    validation: RecordValidation


@dataclass
class ConstDeclStmt:
    field: RecordField
    annotations: list[Annotation] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['decl:const'] | str | None = None
    statement_type: Literal['decl:const'] | None = None


@dataclass
class DestructureBinding:
    name: str
    alias: str | None = None
    default: ExprStmt | None = None
    nested: DestructuringStmt | None = None


@dataclass
class DestructuringStmt:
    annotations: list[Annotation] | None = None
    bindings: list[DestructureBinding] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    declare: str | None = None
    end_line: int | None = None
    isArray: bool | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    rest: str | None = None
    start_line: int | None = None
    statement_refinement: Literal['assignment:destructure'] | str | None = None
    statement_type: Literal['assignment:destructure'] | None = None
    value: ExprStmt | None = None


@dataclass
class Argument:
    name: str | None = None
    value: ExprStmt | None = None


@dataclass
class DispatchCallStmt:
    Method: Node | None = None
    annotations: list[Annotation] | None = None
    arguments: list[Argument] | None = None
    candidates: list[Node] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    receiver: ExprStmt | None = None
    start_line: int | None = None
    statement_refinement: Literal['dispatch_call'] | str | None = None
    statement_type: Literal['dispatch_call'] | None = None


@dataclass
class EndpointCallStmt:
    annotations: list[Annotation] | None = None
    arguments: list[Argument] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    endpoint: Node | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['call:api'] | str | None = None
    statement_type: Literal['call:api'] | None = None


@dataclass
class ExprStmt:
    annotations: list[Annotation] | None = None
    binary: BinaryStmt | None = None
    cast: CastStmt | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    dispatch_call: DispatchCallStmt | None = None
    end_line: int | None = None
    endpoint_call: EndpointCallStmt | None = None
    language: str | None = None
    last_modified: str | None = None
    literal: LiteralStmt | None = None
    method_call: MethodCallStmt | None = None
    object_literal: ObjectLiteralStmt | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    record_read: RecordReadStmt | None = None
    start_line: int | None = None
    statement_refinement: Literal['assignment:expression'] | str | None = None
    statement_type: Literal['assignment:expression'] | None = None
    tuple: TupleStmt | None = None
    unary: UnaryStmt | None = None
    variable: ScopedVariableRef | None = None


@dataclass
class FieldValidation:
    conditions: list[ConditionalFieldValidation] | None = None
    enum: list[str] | None = None
    expressions: list[Expression] | None = None
    hints: list[GeneratorHint] | None = None
    max: float | None = None
    maxDate: str | None = None
    maxExclusive: float | None = None
    maxItems: int | None = None
    maxLength: int | None = None
    maxProperties: int | None = None
    min: float | None = None
    minDate: str | None = None
    minExclusive: float | None = None
    minItems: int | None = None
    minLength: int | None = None
    minProperties: int | None = None
    nonEmpty: bool | None = None
    regex: str | None = None
    required: bool | None = None
    rules: list[ValidationRule] | None = None
    sortedItems: bool | None = None
    unique: bool | None = None
    uniqueItems: bool | None = None
    unitTypes: list[UnitType] | None = None


@dataclass
class ForEachStmt:
    annotations: list[Annotation] | None = None
    body: BlockStmt | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    iterable: ExprStmt | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['control:loop:foreach'] | str | None = None
    statement_type: Literal['control:loop:foreach'] | None = None
    variable: AssignmentStmt | None = None


@dataclass
class ForStmt:
    annotations: list[Annotation] | None = None
    body: BlockStmt | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    cond: ConditionStmt | None = None
    content: str | None = None
    end_line: int | None = None
    init: AssignmentStmt | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['control:loop:for'] | str | None = None
    statement_type: Literal['control:loop:for'] | None = None
    update: ExprStmt | None = None


@dataclass
class FunctionDeclStmt:
    function: MethodNode
    annotations: list[Annotation] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['decl:func'] | str | None = None
    statement_type: Literal['decl:func'] | None = None


@dataclass
class IfStmt:
    annotations: list[Annotation] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    condition: ConditionStmt | None = None
    content: str | None = None
    else_: BlockStmt | None = None
    end_line: int | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['control:if'] | str | None = None
    statement_type: Literal['control:if'] | None = None
    then: BlockStmt | None = None


@dataclass
class MethodCallStmt:
    Method: Node | None = None
    annotations: list[Annotation] | None = None
    arguments: list[Argument] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    is_constructor: bool | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    receiver: ExprStmt | None = None
    start_line: int | None = None
    statement_refinement: Literal['call'] | str | None = None
    statement_type: Literal['call'] | None = None


@dataclass
class MethodNode:
    annotations: list[Annotation] | None = None
    body: BlockStmt | None = None
    comments: list[Comment] | None = None
    errors: list[ASTError] | None = None
    field: str | None = None
    id: str | None = None
    isAsync: bool | None = None
    isGenerator: bool | None = None
    method: str | None = None
    module: str | None = None
    node_kind: Literal['method'] | None = None
    node_type: NodeType | None = None
    package: str | None = None
    params: list[RecordField] | None = None
    properties: dict[str, Any] | None = None
    returnType: TypeReference | None = None
    returns: list[RecordField] | None = None
    signature: str | None = None
    sourceCode: SourceCode | None = None
    type: str | None = None
    typeParams: list[TypeParam] | None = None
    visibility: Visibility | None = None


@dataclass
class ModuleNode:
    annotations: list[Annotation] | None = None
    comments: list[Comment] | None = None
    field: str | None = None
    id: str | None = None
    method: str | None = None
    module: str | None = None
    node_kind: Literal['module'] | None = None
    node_type: NodeType | None = None
    package: str | None = None
    packages: list[PackageNode] | None = None
    properties: dict[str, Any] | None = None
    signature: str | None = None
    sourceCode: SourceCode | None = None
    type: str | None = None


Node: TypeAlias = Union[
    "NodeModuleNode",
    "NodePackageNode",
    "NodeTypedNode",
    "NodeMethodNode",
    "NodeASTRecord",
    "NodeASTEndpoint",
    "NodeRecordField",
    "NodeRecordTable",
    NodeRecordColumn,
    NodeRecordIndex,
    NodeRecordForeignKey,
    NodeNodeRef,
]


@dataclass
class NodeASTEndpoint:
    node_kind: Literal['endpoint']
    annotations: list[Annotation] | None = None
    comments: list[Comment] | None = None
    endpointType: EndpointType | None = None
    errors: list[ASTError] | None = None
    examples: list[str] | None = None
    field: str | None = None
    httpMethod: EndpointPointMethod | None = None
    id: str | None = None
    input: ASTRecord | None = None
    method: str | None = None
    module: str | None = None
    node_type: NodeType | None = None
    output: ASTRecord | None = None
    package: str | None = None
    properties: dict[str, Any] | None = None
    signature: str | None = None
    sourceCode: SourceCode | None = None
    type: str | None = None


@dataclass
class NodeASTRecord:
    node_kind: Literal['record']
    annotations: list[Annotation] | None = None
    comments: list[Comment] | None = None
    description: str | None = None
    examples: list[str] | None = None
    extends: list[ASTRecord] | None = None
    field: str | None = None
    fields: list[RecordField] | None = None
    id: str | None = None
    method: str | None = None
    module: str | None = None
    node_type: NodeType | None = None
    package: str | None = None
    properties: dict[str, Any] | None = None
    recordType: RecordType | None = None
    references: list[RecordReference] | None = None
    signature: str | None = None
    sourceCode: SourceCode | None = None
    type: str | None = None
    validation: RecordValidation | None = None


@dataclass
class NodeMethodNode:
    node_kind: Literal['method']
    annotations: list[Annotation] | None = None
    body: BlockStmt | None = None
    comments: list[Comment] | None = None
    errors: list[ASTError] | None = None
    field: str | None = None
    id: str | None = None
    isAsync: bool | None = None
    isGenerator: bool | None = None
    method: str | None = None
    module: str | None = None
    node_type: NodeType | None = None
    package: str | None = None
    params: list[RecordField] | None = None
    properties: dict[str, Any] | None = None
    returnType: TypeReference | None = None
    returns: list[RecordField] | None = None
    signature: str | None = None
    sourceCode: SourceCode | None = None
    type: str | None = None
    typeParams: list[TypeParam] | None = None
    visibility: Visibility | None = None


@dataclass
class NodeModuleNode:
    node_kind: Literal['module']
    annotations: list[Annotation] | None = None
    comments: list[Comment] | None = None
    field: str | None = None
    id: str | None = None
    method: str | None = None
    module: str | None = None
    node_type: NodeType | None = None
    package: str | None = None
    packages: list[PackageNode] | None = None
    properties: dict[str, Any] | None = None
    signature: str | None = None
    sourceCode: SourceCode | None = None
    type: str | None = None


@dataclass
class NodePackageNode:
    node_kind: Literal['package']
    annotations: list[Annotation] | None = None
    comments: list[Comment] | None = None
    endpoints: list[ASTEndpoint] | None = None
    field: str | None = None
    functions: list[MethodNode] | None = None
    id: str | None = None
    initFunctions: list[MethodNode] | None = None
    method: str | None = None
    module: str | None = None
    node_type: NodeType | None = None
    package: str | None = None
    properties: dict[str, Any] | None = None
    records: list[ASTRecord] | None = None
    signature: str | None = None
    sourceCode: SourceCode | None = None
    tables: list[RecordTable] | None = None
    type: str | None = None
    types: list[TypedNode] | None = None
    variables: list[RecordField] | None = None


@dataclass
class NodeRecordField:
    fieldType: RecordFieldType | Literal['']
    node_kind: Literal['record_field']
    annotations: list[Annotation] | None = None
    comments: list[Comment] | None = None
    defaultValue: TypedValue | None = None
    field: str | None = None
    id: str | None = None
    label: str | None = None
    method: str | None = None
    module: str | None = None
    node_type: NodeType | None = None
    package: str | None = None
    properties: dict[str, Any] | None = None
    readOnly: bool | None = None
    signature: str | None = None
    sourceCode: SourceCode | None = None
    type: str | None = None
    typeRef: TypeReference | None = None
    validation: FieldValidation | None = None
    visibility: Visibility | None = None
    writeOnly: bool | None = None


@dataclass
class NodeRecordTable:
    node_kind: Literal['table']
    annotations: list[Annotation] | None = None
    columns: list[RecordColumn] | None = None
    comments: list[Comment] | None = None
    description: str | None = None
    extends: list[ASTRecord] | None = None
    field: str | None = None
    foreignKeys: list[RecordForeignKey] | None = None
    id: str | None = None
    indexes: list[RecordIndex] | None = None
    method: str | None = None
    module: str | None = None
    node_type: NodeType | None = None
    package: str | None = None
    primaryKey: list[str] | None = None
    properties: dict[str, Any] | None = None
    recordType: RecordType | None = None
    rowCount: int | None = None
    signature: str | None = None
    sourceCode: SourceCode | None = None
    type: str | None = None


@dataclass
class NodeTypedNode:
    node_kind: Literal['class']
    annotations: list[Annotation] | None = None
    comments: list[Comment] | None = None
    constructor: MethodNode | None = None
    destructor: MethodNode | None = None
    extends: TypeReference | None = None
    field: str | None = None
    id: str | None = None
    implements: list[TypeReference] | None = None
    isAbstract: bool | None = None
    method: str | None = None
    methods: list[MethodNode] | None = None
    module: str | None = None
    node_type: NodeType | None = None
    package: str | None = None
    properties: dict[str, Any] | None = None
    signature: str | None = None
    sourceCode: SourceCode | None = None
    type: str | None = None
    typeParams: list[TypeParam] | None = None
    types: list[TypedNode] | None = None
    variables: list[RecordField] | None = None
    visibility: Visibility | None = None


@dataclass
class ObjectLiteralEntry:
    key: str | None = None
    value: ExprStmt | None = None


@dataclass
class ObjectLiteralStmt:
    annotations: list[Annotation] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    entries: list[ObjectLiteralEntry] | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['assignment:object'] | str | None = None
    statement_type: Literal['assignment:object'] | None = None


@dataclass
class PackageNode:
    annotations: list[Annotation] | None = None
    comments: list[Comment] | None = None
    endpoints: list[ASTEndpoint] | None = None
    field: str | None = None
    functions: list[MethodNode] | None = None
    id: str | None = None
    initFunctions: list[MethodNode] | None = None
    method: str | None = None
    module: str | None = None
    node_kind: Literal['package'] | None = None
    node_type: NodeType | None = None
    package: str | None = None
    properties: dict[str, Any] | None = None
    records: list[ASTRecord] | None = None
    signature: str | None = None
    sourceCode: SourceCode | None = None
    tables: list[RecordTable] | None = None
    type: str | None = None
    types: list[TypedNode] | None = None
    variables: list[RecordField] | None = None


@dataclass
class RecordField:
    fieldType: RecordFieldType | Literal['']
    annotations: list[Annotation] | None = None
    comments: list[Comment] | None = None
    defaultValue: TypedValue | None = None
    field: str | None = None
    id: str | None = None
    label: str | None = None
    method: str | None = None
    module: str | None = None
    node_kind: Literal['record_field'] | None = None
    node_type: NodeType | None = None
    package: str | None = None
    properties: dict[str, Any] | None = None
    readOnly: bool | None = None
    signature: str | None = None
    sourceCode: SourceCode | None = None
    type: str | None = None
    typeRef: TypeReference | None = None
    validation: FieldValidation | None = None
    visibility: Visibility | None = None
    writeOnly: bool | None = None


@dataclass
class RecordReadStmt:
    expression: Expression
    Record: Node | None = None
    annotations: list[Annotation] | None = None
    arguments: list[Argument] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    recordType: RecordType | None = None
    start_line: int | None = None
    statement_refinement: Literal['call:read:record'] | str | None = None
    statement_type: Literal['call:read:record'] | None = None


@dataclass
class RecordTable:
    annotations: list[Annotation] | None = None
    columns: list[RecordColumn] | None = None
    comments: list[Comment] | None = None
    description: str | None = None
    extends: list[ASTRecord] | None = None
    field: str | None = None
    foreignKeys: list[RecordForeignKey] | None = None
    id: str | None = None
    indexes: list[RecordIndex] | None = None
    method: str | None = None
    module: str | None = None
    node_kind: Literal['table'] | None = None
    node_type: NodeType | None = None
    package: str | None = None
    primaryKey: list[str] | None = None
    properties: dict[str, Any] | None = None
    recordType: RecordType | None = None
    rowCount: int | None = None
    signature: str | None = None
    sourceCode: SourceCode | None = None
    type: str | None = None


@dataclass
class RecordValidation:
    allOf: list[str] | None = None
    anyOf: list[str] | None = None
    conditions: list[ConditionalRecordValidation] | None = None
    expressions: list[Expression] | None = None
    hints: list[GeneratorHint] | None = None
    maxRecords: int | None = None
    minRecords: int | None = None
    noneOf: list[str] | None = None
    oneOf: list[str] | None = None
    uniqueFields: list[str] | None = None


@dataclass
class RecordWriteStmt:
    expression: Expression
    Record: Node | None = None
    annotations: list[Annotation] | None = None
    arguments: list[Argument] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    recordType: RecordType | None = None
    start_line: int | None = None
    statement_refinement: Literal['call:write:record'] | str | None = None
    statement_type: Literal['call:write:record'] | None = None


@dataclass
class ReturnStmt:
    annotations: list[Annotation] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['control:return'] | str | None = None
    statement_type: Literal['control:return'] | None = None
    value: ExprStmt | None = None


Statement: TypeAlias = Union[
    "StatementAssignmentStmt",
    "StatementBinaryStmt",
    "StatementBlockStmt",
    StatementBreakStmt,
    "StatementCastStmt",
    "StatementConditionStmt",
    "StatementConstDeclStmt",
    StatementContinueStmt,
    "StatementEndpointCallStmt",
    "StatementExprStmt",
    "StatementForStmt",
    "StatementForEachStmt",
    "StatementFunctionDeclStmt",
    "StatementIfStmt",
    StatementLiteralStmt,
    "StatementMethodCallStmt",
    "StatementDispatchCallStmt",
    "StatementRecordReadStmt",
    "StatementRecordWriteStmt",
    "StatementReturnStmt",
    "StatementSwitchStmt",
    "StatementThrowStmt",
    "StatementTryStmt",
    "StatementTupleStmt",
    "StatementObjectLiteralStmt",
    StatementTypeDeclStmt,
    "StatementUnaryStmt",
    "StatementVariableDeclStmt",
    StatementVariableStmt,
    "StatementWhileStmt",
    StatementDocStmt,
    "StatementTestStmt",
    StatementRawStmt,
    "StatementDestructuringStmt",
    "StatementTemplateLiteralStmt",
    StatementScopedVariableRef,
]


@dataclass
class StatementAssignmentStmt:
    statement_type: Literal['assignment']
    annotations: list[Annotation] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    isDeclaration: bool | None = None
    language: str | None = None
    last_modified: str | None = None
    op: AssignmentOp | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['assignment'] | str | None = None
    target: ScopedVariableRef | None = None
    value: ExprStmt | None = None


@dataclass
class StatementBinaryStmt:
    statement_type: Literal['assignment:binary']
    annotations: list[Annotation] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    language: str | None = None
    last_modified: str | None = None
    left: ExprStmt | None = None
    op: BinaryOp | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    right: ExprStmt | None = None
    start_line: int | None = None
    statement_refinement: Literal['assignment:binary'] | str | None = None


@dataclass
class StatementBlockStmt:
    statement_type: Literal['control:block']
    annotations: list[Annotation] | None = None
    children: list[Statement] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['control:block'] | str | Literal['doc'] | None = None
    variables: list[RecordField] | None = None


@dataclass
class StatementCastStmt:
    statement_type: Literal['assignment:cast']
    annotations: list[Annotation] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    expr: ExprStmt | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['assignment:cast'] | str | None = None
    targetType: str | None = None


@dataclass
class StatementConditionStmt:
    statement_type: Literal['control:condition']
    annotations: list[Annotation] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    expr: ExprStmt | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['control:condition'] | str | None = None


@dataclass
class StatementConstDeclStmt:
    field: RecordField
    statement_type: Literal['decl:const']
    annotations: list[Annotation] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['decl:const'] | str | None = None


@dataclass
class StatementDestructuringStmt:
    statement_type: Literal['assignment:destructure']
    annotations: list[Annotation] | None = None
    bindings: list[DestructureBinding] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    declare: str | None = None
    end_line: int | None = None
    isArray: bool | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    rest: str | None = None
    start_line: int | None = None
    statement_refinement: Literal['assignment:destructure'] | str | None = None
    value: ExprStmt | None = None


@dataclass
class StatementDispatchCallStmt:
    statement_type: Literal['dispatch_call']
    Method: Node | None = None
    annotations: list[Annotation] | None = None
    arguments: list[Argument] | None = None
    candidates: list[Node] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    receiver: ExprStmt | None = None
    start_line: int | None = None
    statement_refinement: Literal['dispatch_call'] | str | None = None


@dataclass
class StatementEndpointCallStmt:
    statement_type: Literal['call:api']
    annotations: list[Annotation] | None = None
    arguments: list[Argument] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    endpoint: Node | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['call:api'] | str | None = None


@dataclass
class StatementExprStmt:
    statement_type: Literal['assignment:expression']
    annotations: list[Annotation] | None = None
    binary: BinaryStmt | None = None
    cast: CastStmt | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    dispatch_call: DispatchCallStmt | None = None
    end_line: int | None = None
    endpoint_call: EndpointCallStmt | None = None
    language: str | None = None
    last_modified: str | None = None
    literal: LiteralStmt | None = None
    method_call: MethodCallStmt | None = None
    object_literal: ObjectLiteralStmt | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    record_read: RecordReadStmt | None = None
    start_line: int | None = None
    statement_refinement: Literal['assignment:expression'] | str | None = None
    tuple: TupleStmt | None = None
    unary: UnaryStmt | None = None
    variable: ScopedVariableRef | None = None


@dataclass
class StatementForEachStmt:
    statement_type: Literal['control:loop:foreach']
    annotations: list[Annotation] | None = None
    body: BlockStmt | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    iterable: ExprStmt | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['control:loop:foreach'] | str | None = None
    variable: AssignmentStmt | None = None


@dataclass
class StatementForStmt:
    statement_type: Literal['control:loop:for']
    annotations: list[Annotation] | None = None
    body: BlockStmt | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    cond: ConditionStmt | None = None
    content: str | None = None
    end_line: int | None = None
    init: AssignmentStmt | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['control:loop:for'] | str | None = None
    update: ExprStmt | None = None


@dataclass
class StatementFunctionDeclStmt:
    function: MethodNode
    statement_type: Literal['decl:func']
    annotations: list[Annotation] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['decl:func'] | str | None = None


@dataclass
class StatementIfStmt:
    statement_type: Literal['control:if']
    annotations: list[Annotation] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    condition: ConditionStmt | None = None
    content: str | None = None
    else_: BlockStmt | None = None
    end_line: int | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['control:if'] | str | None = None
    then: BlockStmt | None = None


@dataclass
class StatementMethodCallStmt:
    statement_type: Literal['call']
    Method: Node | None = None
    annotations: list[Annotation] | None = None
    arguments: list[Argument] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    is_constructor: bool | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    receiver: ExprStmt | None = None
    start_line: int | None = None
    statement_refinement: Literal['call'] | str | None = None


@dataclass
class StatementObjectLiteralStmt:
    statement_type: Literal['assignment:object']
    annotations: list[Annotation] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    entries: list[ObjectLiteralEntry] | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['assignment:object'] | str | None = None


@dataclass
class StatementRecordReadStmt:
    expression: Expression
    statement_type: Literal['call:read:record']
    Record: Node | None = None
    annotations: list[Annotation] | None = None
    arguments: list[Argument] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    recordType: RecordType | None = None
    start_line: int | None = None
    statement_refinement: Literal['call:read:record'] | str | None = None


@dataclass
class StatementRecordWriteStmt:
    expression: Expression
    statement_type: Literal['call:write:record']
    Record: Node | None = None
    annotations: list[Annotation] | None = None
    arguments: list[Argument] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    recordType: RecordType | None = None
    start_line: int | None = None
    statement_refinement: Literal['call:write:record'] | str | None = None


@dataclass
class StatementReturnStmt:
    statement_type: Literal['control:return']
    annotations: list[Annotation] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['control:return'] | str | None = None
    value: ExprStmt | None = None


@dataclass
class Case:
    body: BlockStmt | None = None
    condition: ConditionStmt | None = None


@dataclass
class StatementSwitchStmt:
    statement_type: Literal['control:switch']
    annotations: list[Annotation] | None = None
    cases: list[Case] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['control:switch'] | str | None = None
    value: ExprStmt | None = None


@dataclass
class StatementTemplateLiteralStmt:
    statement_type: Literal['assignment:template']
    strings: list[str] | None
    annotations: list[Annotation] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    expressions: list[ExprStmt] | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['assignment:template'] | str | None = None
    tag: ExprStmt | None = None


@dataclass
class StatementTestStmt:
    statement_type: Literal['test']
    annotations: list[Annotation] | None = None
    children: list[Statement] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    language: str | None = None
    last_modified: str | None = None
    name: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['test'] | str | None = None
    variables: list[RecordField] | None = None


@dataclass
class StatementThrowStmt:
    statement_type: Literal['control:throw']
    annotations: list[Annotation] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    exception: ExprStmt | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['control:throw'] | str | None = None


@dataclass
class StatementTryStmt:
    statement_type: Literal['control:try']
    annotations: list[Annotation] | None = None
    body: BlockStmt | None = None
    catch: BlockStmt | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['control:try'] | str | None = None


@dataclass
class StatementTupleStmt:
    statement_type: Literal['assignment:tuple']
    annotations: list[Annotation] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    elements: list[ExprStmt] | None = None
    end_line: int | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['assignment:tuple'] | str | None = None


@dataclass
class StatementUnaryStmt:
    statement_type: Literal['assignment:unary']
    annotations: list[Annotation] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    language: str | None = None
    last_modified: str | None = None
    op: UnaryOp | None = None
    operand: ExprStmt | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['assignment:unary'] | str | None = None


@dataclass
class StatementVariableDeclStmt:
    field: RecordField
    statement_type: Literal['decl:var']
    annotations: list[Annotation] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['decl:var'] | str | None = None


@dataclass
class StatementWhileStmt:
    statement_type: Literal['control:loop:while']
    annotations: list[Annotation] | None = None
    body: BlockStmt | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    condition: ConditionStmt | None = None
    content: str | None = None
    end_line: int | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['control:loop:while'] | str | None = None


@dataclass
class SwitchStmt:
    annotations: list[Annotation] | None = None
    cases: list[Case] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['control:switch'] | str | None = None
    statement_type: Literal['control:switch'] | None = None
    value: ExprStmt | None = None


@dataclass
class TemplateLiteralStmt:
    strings: list[str] | None
    annotations: list[Annotation] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    expressions: list[ExprStmt] | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['assignment:template'] | str | None = None
    statement_type: Literal['assignment:template'] | None = None
    tag: ExprStmt | None = None


@dataclass
class TestStmt:
    annotations: list[Annotation] | None = None
    children: list[Statement] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    language: str | None = None
    last_modified: str | None = None
    name: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['test'] | str | None = None
    statement_type: Literal['test'] | None = None
    variables: list[RecordField] | None = None


@dataclass
class ThrowStmt:
    annotations: list[Annotation] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    exception: ExprStmt | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['control:throw'] | str | None = None
    statement_type: Literal['control:throw'] | None = None


@dataclass
class TryStmt:
    annotations: list[Annotation] | None = None
    body: BlockStmt | None = None
    catch: BlockStmt | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['control:try'] | str | None = None
    statement_type: Literal['control:try'] | None = None


@dataclass
class TupleStmt:
    annotations: list[Annotation] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    elements: list[ExprStmt] | None = None
    end_line: int | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['assignment:tuple'] | str | None = None
    statement_type: Literal['assignment:tuple'] | None = None


@dataclass
class TypedNode:
    annotations: list[Annotation] | None = None
    comments: list[Comment] | None = None
    constructor: MethodNode | None = None
    destructor: MethodNode | None = None
    extends: TypeReference | None = None
    field: str | None = None
    id: str | None = None
    implements: list[TypeReference] | None = None
    isAbstract: bool | None = None
    method: str | None = None
    methods: list[MethodNode] | None = None
    module: str | None = None
    node_kind: Literal['class'] | None = None
    node_type: NodeType | None = None
    package: str | None = None
    properties: dict[str, Any] | None = None
    signature: str | None = None
    sourceCode: SourceCode | None = None
    type: str | None = None
    typeParams: list[TypeParam] | None = None
    types: list[TypedNode] | None = None
    variables: list[RecordField] | None = None
    visibility: Visibility | None = None


@dataclass
class UIRModel:
    endpoints: list[ASTEndpoint] | None = None
    functions: list[MethodNode] | None = None
    hierarchy: HierarchyGraph | None = None
    modules: list[ModuleNode] | None = None
    packages: list[PackageNode] | None = None
    rawFiles: list[RawFile] | None = None
    records: list[ASTRecord] | None = None
    tables: list[RecordTable] | None = None
    types: list[TypedNode] | None = None


@dataclass
class UnaryStmt:
    annotations: list[Annotation] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    language: str | None = None
    last_modified: str | None = None
    op: UnaryOp | None = None
    operand: ExprStmt | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['assignment:unary'] | str | None = None
    statement_type: Literal['assignment:unary'] | None = None


@dataclass
class VariableDeclStmt:
    field: RecordField
    annotations: list[Annotation] | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    content: str | None = None
    end_line: int | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['decl:var'] | str | None = None
    statement_type: Literal['decl:var'] | None = None


@dataclass
class WhileStmt:
    annotations: list[Annotation] | None = None
    body: BlockStmt | None = None
    column: int | None = None
    comments: list[Comment] | None = None
    condition: ConditionStmt | None = None
    content: str | None = None
    end_line: int | None = None
    language: str | None = None
    last_modified: str | None = None
    path: str | None = None
    properties: dict[str, Any] | None = None
    start_line: int | None = None
    statement_refinement: Literal['control:loop:while'] | str | None = None
    statement_type: Literal['control:loop:while'] | None = None
